-- MySQL Script generated by MySQL Workbench
-- 10/09/15 17:55:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`loja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`loja` (
  `idLoja` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `descricao` VARCHAR(45) NOT NULL COMMENT '',
  `nomeFantasia` VARCHAR(45) NOT NULL COMMENT '',
  `razaoSocial` VARCHAR(60) NOT NULL COMMENT '',
  `tel` VARCHAR(18) NOT NULL COMMENT '',
  `tel2` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `inscEstadual` VARCHAR(20) NOT NULL COMMENT '',
  `sigla` VARCHAR(4) NOT NULL COMMENT '',
  `cnpj` VARCHAR(18) NOT NULL COMMENT '',
  `codUF` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `porcentagemFrete` INT(11) NOT NULL DEFAULT '4' COMMENT '',
  `valorMinimoFrete` INT(11) NOT NULL DEFAULT '80' COMMENT '',
  `servidorACBr` VARCHAR(45) NOT NULL DEFAULT 'localhost' COMMENT '',
  `portaACBr` INT(11) NOT NULL DEFAULT '3436' COMMENT '',
  `pastaEntACBr` VARCHAR(100) NOT NULL DEFAULT 'C:/ACBrNFeMonitor/ENTNFE.TXT/' COMMENT '',
  `pastaSaiACBr` VARCHAR(100) NOT NULL DEFAULT 'C:/ACBrNFeMonitor/SAINFE.TXT/' COMMENT '',
  `pastaXmlACBr` VARCHAR(100) NOT NULL DEFAULT 'C:/ACBrNFeMonitor/XML/' COMMENT '',
  `servidorSMTP` VARCHAR(100) NULL COMMENT '',
  `portaSMTP` VARCHAR(100) NULL COMMENT '',
  `emailCompra` VARCHAR(100) NULL COMMENT '',
  `emailSenha` VARCHAR(100) NULL COMMENT '',
  `pastaCompra` VARCHAR(100) NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idLoja`)  COMMENT '',
  UNIQUE INDEX `idLoja_UNIQUE` (`idLoja` ASC)  COMMENT '',
  FULLTEXT INDEX `idxFT` (`descricao` ASC, `nomeFantasia` ASC, `razaoSocial` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`alcadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alcadas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alcadas` (
  `idAlcada` INT(11) NOT NULL COMMENT '',
  `idLoja` INT(10) UNSIGNED NOT NULL COMMENT '',
  `tipoFuncionario` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '',
  `debito` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `credito` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `cheque` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `dinheiro` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `boleto` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  PRIMARY KEY (`idAlcada`, `idLoja`)  COMMENT '',
  UNIQUE INDEX `idAlcada_UNIQUE` (`idAlcada` ASC)  COMMENT '',
  INDEX `fk_Alçadas_Loja1_idx` (`idLoja` ASC)  COMMENT '',
  CONSTRAINT `fk_Alçadas_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`profissional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profissional` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profissional` (
  `idProfissional` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `pfpj` VARCHAR(45) NULL COMMENT '',
  `nome_razao` VARCHAR(45) NOT NULL COMMENT '',
  `nomeFantasia` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cpf` VARCHAR(14) NULL DEFAULT NULL COMMENT '',
  `cnpj` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `rg` VARCHAR(12) NULL DEFAULT NULL COMMENT '',
  `inscEstadual` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoNome` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoCPF` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoApelido` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoRG` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `tel` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `telCel` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `telCom` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `idNextel` VARCHAR(16) NULL DEFAULT NULL COMMENT '',
  `nextel` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `tipoProf` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `banco` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `agencia` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cc` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `nomeBanco` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cpfBanco` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `incompleto` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idProfissional`)  COMMENT '',
  FULLTEXT INDEX `idxFT` (`nome_razao` ASC, `tipoProf` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `idLoja` INT(10) UNSIGNED NOT NULL COMMENT '',
  `user` VARCHAR(20) NOT NULL COMMENT '',
  `passwd` VARCHAR(42) NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `sigla` VARCHAR(3) NOT NULL COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idUsuario`)  COMMENT '',
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC)  COMMENT '',
  UNIQUE INDEX `user_UNIQUE` (`user` ASC)  COMMENT '',
  INDEX `fk_Usuario_Loja1_idx` (`idLoja` ASC)  COMMENT '',
  FULLTEXT INDEX `idxFT` (`nome` ASC, `tipo` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `pfpj` VARCHAR(45) NOT NULL COMMENT '',
  `nome_razao` VARCHAR(45) NOT NULL COMMENT '',
  `nomeFantasia` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cpf` VARCHAR(14) NULL DEFAULT NULL COMMENT '',
  `cnpj` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `rg` VARCHAR(12) NULL DEFAULT NULL COMMENT '',
  `dataNasc` DATE NULL DEFAULT NULL COMMENT '',
  `inscEstadual` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoNome` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoCPF` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoApelido` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoRG` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `tel` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `telCel` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `telCom` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `idNextel` VARCHAR(16) NULL DEFAULT NULL COMMENT '',
  `nextel` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `idUsuarioRel` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `idCadastroRel` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `idProfissionalRel` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `incompleto` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idCliente`)  COMMENT '',
  INDEX `fk_Cliente_Usuario1_idx` (`idUsuarioRel` ASC)  COMMENT '',
  INDEX `fk_Cliente_Cliente1_idx` (`idCadastroRel` ASC)  COMMENT '',
  INDEX `fk_Cliente_Profissional1_idx` (`idProfissionalRel` ASC)  COMMENT '',
  INDEX `fk_Cadastro_Produto_idx` (`idCliente` ASC)  COMMENT '',
  FULLTEXT INDEX `idxFT` (`nome_razao` ASC, `nomeFantasia` ASC, `cpf` ASC, `cnpj` ASC)  COMMENT '',
  CONSTRAINT `fk_Cliente_Cliente1`
    FOREIGN KEY (`idCadastroRel`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Profissional1`
    FOREIGN KEY (`idProfissionalRel`)
    REFERENCES `mydb`.`profissional` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`idUsuarioRel`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente_has_endereco` (
  `idEndereco` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `idCliente` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `descricao` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cep` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `logradouro` VARCHAR(90) NULL DEFAULT NULL COMMENT '',
  `numero` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `complemento` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `bairro` VARCHAR(72) NULL DEFAULT NULL COMMENT '',
  `cidade` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `uf` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `codUF` INT(11) NULL DEFAULT NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idEndereco`)  COMMENT '',
  INDEX `fk_Cliente_has_Endereco_Cliente1_idx` (`idCliente` ASC)  COMMENT '',
  CONSTRAINT `fk_Cliente_has_Endereco_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`conta_a_pagar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta_a_pagar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta_a_pagar` (
  `idContaPagar` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idVenda` VARCHAR(20) NOT NULL COMMENT '',
  `dataEmissao` DATETIME NOT NULL COMMENT '',
  `dataPagamento` DATETIME NULL DEFAULT NULL COMMENT '',
  `pago` VARCHAR(5) NOT NULL DEFAULT 'NÃO' COMMENT '',
  `formaPagamento` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `idProduto` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idContaPagar`, `idVenda`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`conta_a_pagar_has_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta_a_pagar_has_pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta_a_pagar_has_pagamento` (
  `idPagamento` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idVenda` VARCHAR(20) NOT NULL COMMENT '',
  `idLoja` INT(10) UNSIGNED NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `parcela` INT(11) NOT NULL COMMENT '',
  `valor` DECIMAL(15,2) NOT NULL COMMENT '',
  `data` DATE NOT NULL COMMENT '',
  `observacao` VARCHAR(200) NOT NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDENTE' COMMENT '',
  PRIMARY KEY (`idPagamento`, `idVenda`, `idLoja`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`conta_a_receber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta_a_receber` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta_a_receber` (
  `idContaReceber` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idVenda` VARCHAR(20) NOT NULL COMMENT '',
  `dataEmissao` DATETIME NOT NULL COMMENT '',
  `dataPagamento` DATETIME NULL DEFAULT NULL COMMENT '',
  `pago` VARCHAR(5) NOT NULL DEFAULT 'NÃO' COMMENT '',
  `formaPagamento` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `idProduto` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idContaReceber`, `idVenda`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`conta_a_receber_has_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta_a_receber_has_pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta_a_receber_has_pagamento` (
  `idPagamento` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idVenda` VARCHAR(20) NOT NULL COMMENT '',
  `idLoja` INT(10) UNSIGNED NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `parcela` INT(11) NOT NULL COMMENT '',
  `valor` DECIMAL(15,2) NOT NULL COMMENT '',
  `data` DATE NOT NULL COMMENT '',
  `observacao` VARCHAR(200) NOT NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDENTE' COMMENT '',
  PRIMARY KEY (`idPagamento`, `idVenda`, `idLoja`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `idFornecedor` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `razaoSocial` VARCHAR(45) NOT NULL COMMENT '',
  `nomeFantasia` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cnpj` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `inscEstadual` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoNome` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoCPF` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoApelido` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `contatoRG` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `tel` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `telCel` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `telCom` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `idNextel` VARCHAR(16) NULL DEFAULT NULL COMMENT '',
  `nextel` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `email` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `idUsuarioRel` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `idCadastroRel` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `idProfissionalRel` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `incompleto` TINYINT(1) NULL DEFAULT NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idFornecedor`)  COMMENT '',
  INDEX `fk_Fornecedor_Usuario1_idx` (`idUsuarioRel` ASC)  COMMENT '',
  INDEX `fk_Fornecedor_Fornecedor1_idx` (`idCadastroRel` ASC)  COMMENT '',
  INDEX `fk_Fornecedor_Profissional1_idx` (`idProfissionalRel` ASC)  COMMENT '',
  FULLTEXT INDEX `idxFT` (`razaoSocial` ASC, `nomeFantasia` ASC, `cnpj` ASC)  COMMENT '',
  CONSTRAINT `fk_Fornecedor_Fornecedor1`
    FOREIGN KEY (`idCadastroRel`)
    REFERENCES `mydb`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_Profissional1`
    FOREIGN KEY (`idProfissionalRel`)
    REFERENCES `mydb`.`profissional` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_Usuario1`
    FOREIGN KEY (`idUsuarioRel`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fornecedor_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor_has_endereco` (
  `idEndereco` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `idFornecedor` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `descricao` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cep` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `logradouro` VARCHAR(90) NULL DEFAULT NULL COMMENT '',
  `numero` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `complemento` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `bairro` VARCHAR(72) NULL DEFAULT NULL COMMENT '',
  `cidade` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `uf` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `codUF` INT(11) NULL DEFAULT NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idEndereco`)  COMMENT '',
  INDEX `fk_Fornecedor_has_Endereco_Fornecedor1_idx` (`idFornecedor` ASC)  COMMENT '',
  CONSTRAINT `fk_Fornecedor_has_Endereco_Fornecedor1`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `mydb`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`log` ;

CREATE TABLE IF NOT EXISTS `mydb`.`log` (
  `idLog` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `usuario` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `tipoOperacao` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `data` DATETIME NOT NULL COMMENT '',
  `log` VARCHAR(400) NOT NULL COMMENT '',
  PRIMARY KEY (`idLog`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`loja_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`loja_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`loja_has_endereco` (
  `idEndereco` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `idLoja` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `descricao` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cep` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `logradouro` VARCHAR(90) NULL DEFAULT NULL COMMENT '',
  `numero` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `complemento` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `bairro` VARCHAR(72) NULL DEFAULT NULL COMMENT '',
  `cidade` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `uf` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `codUF` INT(11) NULL DEFAULT NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idEndereco`)  COMMENT '',
  INDEX `fk_Loja_has_Endereco_Loja1_idx` (`idLoja` ASC)  COMMENT '',
  CONSTRAINT `fk_Loja_has_Endereco_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`nfe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nfe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nfe` (
  `idNFe` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `idVendaCompra` VARCHAR(20) NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `xml` MEDIUMTEXT NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDENTE' COMMENT '',
  `chaveAcesso` VARCHAR(50) NOT NULL COMMENT '',
  `obs` VARCHAR(500) NULL COMMENT '',
  PRIMARY KEY (`idNFe`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`orcamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orcamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orcamento` (
  `idOrcamento` VARCHAR(20) NOT NULL COMMENT '',
  `idLoja` INT(10) UNSIGNED NOT NULL COMMENT '',
  `idUsuario` INT(10) UNSIGNED NOT NULL COMMENT '',
  `idCliente` INT(10) UNSIGNED NOT NULL COMMENT '',
  `idEnderecoEntrega` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `idEnderecoFaturamento` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `idProfissional` INT(10) UNSIGNED NOT NULL COMMENT '',
  `data` DATETIME NOT NULL COMMENT '',
  `subTotalBru` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `subTotalLiq` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `frete` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `descontoPorc` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `descontoReais` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `total` DECIMAL(15,2) NOT NULL COMMENT '',
  `validade` INT(11) NOT NULL DEFAULT '7' COMMENT '',
  `status` VARCHAR(45) NOT NULL DEFAULT 'ATIVO' COMMENT '',
  `motivoCancelamento` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `observacao` VARCHAR(300) NULL COMMENT '',
  `prazoEntrega` VARCHAR(100) NULL COMMENT '',
  PRIMARY KEY (`idOrcamento`, `idLoja`)  COMMENT '',
  UNIQUE INDEX `idOrcamento_UNIQUE` (`idOrcamento` ASC)  COMMENT '',
  INDEX `fk_Orcamento_Cliente1_idx` (`idCliente` ASC)  COMMENT '',
  INDEX `fk_Orcamento_Loja1_idx` (`idLoja` ASC)  COMMENT '',
  INDEX `fk_Orcamento_Usuario1_idx` (`idUsuario` ASC)  COMMENT '',
  INDEX `fk_Orcamento_Profissional1_idx` (`idProfissional` ASC)  COMMENT '',
  CONSTRAINT `fk_Orcamento_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orcamento_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orcamento_Profissional1`
    FOREIGN KEY (`idProfissional`)
    REFERENCES `mydb`.`profissional` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orcamento_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idProduto` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `idProdutoUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `idFornecedor` INT(10) UNSIGNED NOT NULL COMMENT '',
  `idFornecedorUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `fornecedor` VARCHAR(100) NOT NULL COMMENT '',
  `fornecedorUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `descricao` VARCHAR(150) NOT NULL COMMENT '',
  `descricaoUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `estoque` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `estoqueUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `un` VARCHAR(10) NOT NULL COMMENT '',
  `unUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `colecao` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `colecaoUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `tipo` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `tipoUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `m2cx` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `m2cxUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `pccx` INT(11) NULL DEFAULT NULL COMMENT '',
  `pccxUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `kgcx` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `kgcxUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `formComercial` VARCHAR(100) NULL DEFAULT NULL COMMENT '',
  `formComercialUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `codComercial` VARCHAR(100) NOT NULL COMMENT '',
  `codComercialUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `codBarras` VARCHAR(100) NULL DEFAULT '0' COMMENT '',
  `codBarrasUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `ncm` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `ncmUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `ncmEx` VARCHAR(2) NULL DEFAULT NULL COMMENT '',
  `ncmExUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `cfop` VARCHAR(4) NULL DEFAULT NULL COMMENT '',
  `cfopUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `icms` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `icmsUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `cst` VARCHAR(3) NULL DEFAULT '000' COMMENT '',
  `cstUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `qtdPallet` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `qtdPalletUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `custo` DECIMAL(15,2) NOT NULL COMMENT '',
  `custoUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `ipi` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `ipiUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `st` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `stUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `precoVenda` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `precoVendaUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `markup` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `markupUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `comissao` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `comissaoUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `observacoes` VARCHAR(800) NULL DEFAULT NULL COMMENT '',
  `observacoesUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `origem` INT(11) NULL DEFAULT NULL COMMENT '',
  `origemUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `temLote` VARCHAR(5) NULL DEFAULT 'NÃO' COMMENT '',
  `temLoteUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `ui` VARCHAR(10) NOT NULL DEFAULT '0' COMMENT '',
  `uiUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `validade` DATE NULL DEFAULT NULL COMMENT '',
  `validadeUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `descontinuado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `descontinuadoUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `atualizarTabelaPreco` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `representacao` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idProduto`)  COMMENT '',
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC)  COMMENT '',
  INDEX `fk_Produto_Fornecedor1_idx` (`idFornecedor` ASC)  COMMENT '',
  INDEX `index` (`fornecedor` ASC, `descricao` ASC, `colecao` ASC, `codComercial` ASC, `formComercial` ASC, `ui` ASC)  COMMENT '',
  INDEX `descontinuado` (`descontinuado` ASC)  COMMENT '',
  FULLTEXT INDEX `idxFT` (`fornecedor` ASC, `descricao` ASC, `colecao` ASC, `codComercial` ASC)  COMMENT '',
  CONSTRAINT `fk_Produto_Fornecedor1`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `mydb`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '													';


-- -----------------------------------------------------
-- Table `mydb`.`orcamento_has_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orcamento_has_produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orcamento_has_produto` (
  `idOrcamento` VARCHAR(20) NOT NULL COMMENT '',
  `idLoja` INT(10) UNSIGNED NOT NULL COMMENT '',
  `item` INT(11) NOT NULL COMMENT '',
  `idProduto` INT(10) UNSIGNED NOT NULL COMMENT '',
  `fornecedor` VARCHAR(45) NOT NULL COMMENT '',
  `produto` VARCHAR(150) NULL DEFAULT NULL COMMENT '',
  `obs` VARCHAR(145) NOT NULL COMMENT '',
  `prcUnitario` DECIMAL(15,2) NOT NULL COMMENT '',
  `caixas` INT(11) NOT NULL COMMENT '',
  `quant` DECIMAL(15,2) NOT NULL COMMENT '',
  `un` VARCHAR(45) NOT NULL COMMENT '',
  `unCaixa` DECIMAL(15,2) NOT NULL COMMENT '',
  `codComercial` VARCHAR(100) NOT NULL COMMENT '',
  `formComercial` VARCHAR(100) NOT NULL COMMENT '',
  `parcial` DECIMAL(15,2) NOT NULL COMMENT '',
  `desconto` DECIMAL(15,4) NOT NULL DEFAULT '0.0000' COMMENT '',
  `parcialDesc` DECIMAL(15,2) NOT NULL COMMENT '',
  `descGlobal` DECIMAL(15,2) NOT NULL COMMENT '',
  `total` DECIMAL(15,2) NOT NULL COMMENT '',
  PRIMARY KEY (`idOrcamento`, `idLoja`, `item`, `idProduto`)  COMMENT '',
  INDEX `fk_Orcamento_has_Produto_Produto1_idx` (`idProduto` ASC)  COMMENT '',
  INDEX `fk_Orcamento_has_Produto_Orcamento1_idx` (`idOrcamento` ASC, `idLoja` ASC)  COMMENT '',
  CONSTRAINT `fk_Orcamento_has_Produto_Orcamento1`
    FOREIGN KEY (`idOrcamento` , `idLoja`)
    REFERENCES `mydb`.`orcamento` (`idOrcamento` , `idLoja`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Orcamento_has_Produto_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`transportadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transportadora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transportadora` (
  `idTransportadora` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `razaoSocial` VARCHAR(60) NOT NULL COMMENT '',
  `nomeFantasia` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cnpj` VARCHAR(18) NOT NULL COMMENT '',
  `inscEstadual` VARCHAR(20) NOT NULL COMMENT '',
  `placaVeiculo` VARCHAR(8) NULL DEFAULT NULL COMMENT '',
  `antt` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `tel` VARCHAR(18) NULL DEFAULT NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idTransportadora`)  COMMENT '',
  FULLTEXT INDEX `idxFT` (`razaoSocial` ASC, `nomeFantasia` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_transportadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido_transportadora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido_transportadora` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idTransportadora` INT(10) UNSIGNED NOT NULL COMMENT '',
  `idPedido` VARCHAR(20) NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `dataEmissao` DATETIME NOT NULL COMMENT '',
  `dataEntrega` DATETIME NULL DEFAULT NULL COMMENT '',
  `status` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`, `idTransportadora`, `idPedido`, `tipo`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`id` ASC)  COMMENT '',
  INDEX `fk_PedidoTransportadora_Transportadora1_idx` (`idTransportadora` ASC)  COMMENT '',
  CONSTRAINT `fk_PedidoTransportadora_Transportadora1`
    FOREIGN KEY (`idTransportadora`)
    REFERENCES `mydb`.`transportadora` (`idTransportadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`produto_has_preco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produto_has_preco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produto_has_preco` (
  `idPreco` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idProduto` INT(10) UNSIGNED NOT NULL COMMENT '',
  `preco` DECIMAL(15,4) NULL DEFAULT NULL COMMENT '',
  `validadeInicio` DATE NULL DEFAULT NULL COMMENT '',
  `validadeFim` DATE NULL DEFAULT NULL COMMENT '',
  `expirado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idPreco`, `idProduto`)  COMMENT '',
  INDEX `fk_Produto_has_Preco_Produto1_idx` (`idProduto` ASC)  COMMENT '',
  INDEX `validadeFim` (`validadeFim` ASC, `expirado` ASC)  COMMENT '',
  CONSTRAINT `fk_Produto_has_Preco_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`profissional_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profissional_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profissional_has_endereco` (
  `idEndereco` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `idProfissional` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `descricao` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cep` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `logradouro` VARCHAR(90) NULL DEFAULT NULL COMMENT '',
  `numero` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `complemento` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `bairro` VARCHAR(72) NULL DEFAULT NULL COMMENT '',
  `cidade` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `uf` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `codUF` INT(11) NULL DEFAULT NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idEndereco`)  COMMENT '',
  INDEX `fk_Profissional_has_Endereco_Profissional1_idx` (`idProfissional` ASC)  COMMENT '',
  CONSTRAINT `fk_Profissional_has_Endereco_Profissional1`
    FOREIGN KEY (`idProfissional`)
    REFERENCES `mydb`.`profissional` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`transportadora_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transportadora_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transportadora_has_endereco` (
  `idEndereco` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `idTransportadora` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT '',
  `descricao` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `cep` VARCHAR(10) NULL DEFAULT NULL COMMENT '',
  `logradouro` VARCHAR(90) NULL DEFAULT NULL COMMENT '',
  `numero` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `complemento` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `bairro` VARCHAR(72) NULL DEFAULT NULL COMMENT '',
  `cidade` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `uf` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `codUF` INT(11) NULL DEFAULT NULL COMMENT '',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`idEndereco`)  COMMENT '',
  INDEX `fk_Transportadora_has_Endereco_Transportadora1_idx` (`idTransportadora` ASC)  COMMENT '',
  CONSTRAINT `fk_Transportadora_has_Endereco_Transportadora1`
    FOREIGN KEY (`idTransportadora`)
    REFERENCES `mydb`.`transportadora` (`idTransportadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `idVenda` VARCHAR(20) NOT NULL COMMENT '',
  `idLoja` INT(10) UNSIGNED NOT NULL COMMENT '',
  `idUsuario` INT(10) UNSIGNED NOT NULL COMMENT '',
  `idCliente` INT(10) UNSIGNED NOT NULL COMMENT '',
  `idEnderecoEntrega` INT(10) UNSIGNED NOT NULL COMMENT '',
  `idEnderecoFaturamento` INT(10) UNSIGNED NOT NULL COMMENT '',
  `idProfissional` INT(10) UNSIGNED NOT NULL COMMENT '',
  `data` DATETIME NOT NULL COMMENT '',
  `dataOrc` DATETIME NOT NULL COMMENT '',
  `subTotalBru` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `subTotalLiq` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `frete` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `descontoPorc` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `descontoReais` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `total` DECIMAL(15,2) NOT NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL DEFAULT 'ATIVO' COMMENT '',
  `observacao` VARCHAR(300) NULL DEFAULT NULL COMMENT '',
  `prazoEntrega` DATE NOT NULL COMMENT '',
  PRIMARY KEY (`idVenda`, `idLoja`)  COMMENT '',
  UNIQUE INDEX `idVenda_UNIQUE` (`idVenda` ASC)  COMMENT '',
  INDEX `fk_Venda_Cliente1_idx` (`idCliente` ASC)  COMMENT '',
  INDEX `fk_Venda_Loja1_idx` (`idLoja` ASC)  COMMENT '',
  INDEX `fk_Venda_Usuario1_idx` (`idUsuario` ASC)  COMMENT '',
  INDEX `fk_Venda_Profissional1_idx` (`idProfissional` ASC)  COMMENT '',
  INDEX `fk_Venda_Endereco1_idx` (`idEnderecoEntrega` ASC)  COMMENT '',
  INDEX `fk_Venda_Endereco2_idx` (`idEnderecoFaturamento` ASC)  COMMENT '',
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Endereco1`
    FOREIGN KEY (`idEnderecoEntrega`)
    REFERENCES `mydb`.`cliente_has_endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Endereco2`
    FOREIGN KEY (`idEnderecoFaturamento`)
    REFERENCES `mydb`.`cliente_has_endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Profissional1`
    FOREIGN KEY (`idProfissional`)
    REFERENCES `mydb`.`profissional` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`venda_has_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda_has_produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda_has_produto` (
  `selecionado` TINYINT(1) NULL DEFAULT '0' COMMENT '',
  `idVendaProduto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idNfeSaida` INT NULL COMMENT '',
  `fornecedor` VARCHAR(45) NOT NULL COMMENT '',
  `idVenda` VARCHAR(20) NOT NULL COMMENT '',
  `idLoja` INT(10) UNSIGNED NOT NULL COMMENT '',
  `item` INT(11) NOT NULL COMMENT '',
  `idProduto` INT(10) UNSIGNED NOT NULL COMMENT '',
  `produto` VARCHAR(150) NULL DEFAULT NULL COMMENT '',
  `obs` VARCHAR(145) NOT NULL COMMENT '',
  `prcUnitario` DECIMAL(15,2) NOT NULL COMMENT '',
  `caixas` INT(11) NOT NULL COMMENT '',
  `quant` DECIMAL(15,2) NOT NULL COMMENT '',
  `un` VARCHAR(45) NOT NULL COMMENT '',
  `unCaixa` DECIMAL(15,2) NOT NULL COMMENT '',
  `codComercial` VARCHAR(100) NOT NULL COMMENT '',
  `formComercial` VARCHAR(100) NOT NULL COMMENT '',
  `parcial` DECIMAL(15,2) NOT NULL COMMENT '',
  `desconto` DECIMAL(15,2) NOT NULL DEFAULT '0.00' COMMENT '',
  `parcialDesc` DECIMAL(15,2) NOT NULL COMMENT '',
  `descGlobal` DECIMAL(15,2) NOT NULL COMMENT '',
  `total` DECIMAL(15,2) NOT NULL COMMENT '',
  `status` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `idCompra` INT NULL COMMENT '',
  `dataPrevCompra` DATE NULL COMMENT '',
  `dataRealCompra` DATE NULL COMMENT '',
  `dataPrevConf` DATE NULL COMMENT '',
  `dataRealConf` DATE NULL COMMENT '',
  `dataPrevFat` DATE NULL COMMENT '',
  `dataRealFat` DATE NULL COMMENT '',
  `dataPrevColeta` DATE NULL COMMENT '',
  `dataRealColeta` DATE NULL COMMENT '',
  `dataPrevReceb` DATE NULL COMMENT '',
  `dataRealReceb` DATE NULL COMMENT '',
  `dataPrevEnt` DATE NULL COMMENT '',
  `dataRealEnt` DATE NULL COMMENT '',
  PRIMARY KEY (`idVendaProduto`, `idVenda`, `idLoja`, `item`, `idProduto`)  COMMENT '',
  INDEX `fk_Venda_has_Produto_Produto1_idx` (`idProduto` ASC)  COMMENT '',
  INDEX `fk_Venda_has_Produto_Venda1_idx` (`idVenda` ASC, `idLoja` ASC)  COMMENT '',
  CONSTRAINT `fk_Venda_has_Produto_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_has_Produto_Venda1`
    FOREIGN KEY (`idVenda` , `idLoja`)
    REFERENCES `mydb`.`venda` (`idVenda` , `idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`venda_cancelada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda_cancelada` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda_cancelada` (
  `descricao` VARCHAR(180) NULL DEFAULT NULL COMMENT '',
  `dataCancelamento` DATETIME NULL DEFAULT NULL COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `idCompra` INT(11) NOT NULL DEFAULT 0 COMMENT '',
  `idVendaProduto` INT NOT NULL DEFAULT 0 COMMENT '',
  `local` VARCHAR(100) NOT NULL DEFAULT 'TEMP' COMMENT '',
  `idProduto` INT NULL DEFAULT NULL COMMENT '',
  `idNFe` INT NULL COMMENT '',
  `fornecedor` VARCHAR(100) NULL COMMENT '',
  `descricao` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `vCOFINS` VARCHAR(45) NULL COMMENT '',
  `quant` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `quantUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `un` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `codBarras` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `codComercial` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `ncm` VARCHAR(45) NULL COMMENT '',
  `cfop` VARCHAR(45) NULL COMMENT '',
  `valorUnid` VARCHAR(45) NULL COMMENT '',
  `valor` VARCHAR(45) NULL COMMENT '',
  `codBarrasTrib` VARCHAR(45) NULL COMMENT '',
  `unTrib` VARCHAR(45) NULL COMMENT '',
  `quantTrib` VARCHAR(45) NULL COMMENT '',
  `valorTrib` VARCHAR(45) NULL COMMENT '',
  `desconto` VARCHAR(45) NULL COMMENT '',
  `compoeTotal` VARCHAR(45) NULL COMMENT '',
  `numeroPedido` VARCHAR(45) NULL COMMENT '',
  `itemPedido` VARCHAR(45) NULL COMMENT '',
  `tipoICMS` VARCHAR(45) NULL COMMENT '',
  `orig` VARCHAR(45) NULL COMMENT '',
  `cstICMS` VARCHAR(45) NULL COMMENT '',
  `modBC` VARCHAR(45) NULL COMMENT '',
  `vBC` VARCHAR(45) NULL COMMENT '',
  `pICMS` VARCHAR(45) NULL COMMENT '',
  `vICMS` VARCHAR(45) NULL COMMENT '',
  `modBCST` VARCHAR(45) NULL COMMENT '',
  `pMVAST` VARCHAR(45) NULL COMMENT '',
  `vBCST` VARCHAR(45) NULL COMMENT '',
  `pICMSST` VARCHAR(45) NULL COMMENT '',
  `vICMSST` VARCHAR(45) NULL COMMENT '',
  `cEnq` VARCHAR(45) NULL COMMENT '',
  `cstIPI` VARCHAR(45) NULL COMMENT '',
  `cstPIS` VARCHAR(45) NULL COMMENT '',
  `vBCPIS` VARCHAR(45) NULL COMMENT '',
  `pPIS` VARCHAR(45) NULL COMMENT '',
  `vPIS` VARCHAR(45) NULL COMMENT '',
  `cstCOFINS` VARCHAR(45) NULL COMMENT '',
  `vBCCOFINS` VARCHAR(45) NULL COMMENT '',
  `pCOFINS` VARCHAR(45) NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDENTE' COMMENT '',
  PRIMARY KEY (`idEstoque`, `idCompra`, `idVendaProduto`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_fornecedor_has_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido_fornecedor_has_produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido_fornecedor_has_produto` (
  `selecionado` TINYINT(1) NULL DEFAULT '0' COMMENT '',
  `idPedido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `fornecedor` VARCHAR(45) NOT NULL COMMENT '',
  `idProduto` INT NULL DEFAULT NULL COMMENT '',
  `descricao` VARCHAR(200) NULL DEFAULT NULL COMMENT '',
  `colecao` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `quant` DECIMAL(15,2) NULL DEFAULT NULL COMMENT '',
  `quantUpd` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `un` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `preco` DECIMAL(15,2) NULL COMMENT '',
  `formComercial` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `codComercial` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `codBarras` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `idCompra` VARCHAR(45) NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDENTE' COMMENT '',
  `obs` VARCHAR(200) NULL COMMENT '',
  `dataPrevCompra` DATE NULL COMMENT '',
  `dataRealCompra` DATE NULL COMMENT '',
  `dataPrevConf` DATE NULL COMMENT '',
  `dataRealConf` DATE NULL COMMENT '',
  `dataPrevFat` DATE NULL COMMENT '',
  `dataRealFat` DATE NULL COMMENT '',
  `dataPrevColeta` DATE NULL COMMENT '',
  `dataRealColeta` DATE NULL COMMENT '',
  `dataPrevReceb` DATE NULL COMMENT '',
  `dataRealReceb` DATE NULL COMMENT '',
  `dataPrevEnt` DATE NULL COMMENT '',
  `dataRealEnt` DATE NULL COMMENT '',
  PRIMARY KEY (`idPedido`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta_representacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta_representacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta_representacao` (
  `idContaRepresentacao` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idVenda` VARCHAR(20) NOT NULL COMMENT '',
  `dataEmissao` DATETIME NOT NULL COMMENT '',
  `dataPagamento` DATETIME NULL DEFAULT NULL COMMENT '',
  `pago` VARCHAR(5) NOT NULL DEFAULT 'NÃO' COMMENT '',
  `formaPagamento` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `idProduto` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idContaRepresentacao`, `idVenda`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conta_representacao_has_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta_representacao_has_pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta_representacao_has_pagamento` (
  `idPagamento` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `idVenda` VARCHAR(20) NOT NULL COMMENT '',
  `idLoja` INT(10) UNSIGNED NOT NULL COMMENT '',
  `tipo` VARCHAR(45) NOT NULL COMMENT '',
  `parcela` INT(11) NOT NULL COMMENT '',
  `valor` DECIMAL(15,2) NOT NULL COMMENT '',
  `data` DATE NOT NULL COMMENT '',
  `observacao` VARCHAR(200) NOT NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDENTE' COMMENT '',
  PRIMARY KEY (`idPagamento`, `idVenda`, `idLoja`)  COMMENT '')
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_estoque` (`Fornecedor` INT, `Produto` INT, `Quant` INT, `Cód Com` INT, `Status` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_orcamento` (`Código` INT, `Cliente` INT, `Total` INT, `Data de emissão` INT, `Status` INT, `Dias restantes` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_venda` (`idVenda` INT, `Loja` INT, `Vendedor` INT, `Cliente` INT, `Endereço` INT, `Profissional` INT, `Data` INT, `Bruto` INT, `Líquido` INT, `Frete` INT, `Total R$` INT, `Status` INT, `Dias restantes` INT);

-- -----------------------------------------------------
-- procedure invalidate_expired
-- -----------------------------------------------------

USE `mydb`;
DROP procedure IF EXISTS `mydb`.`invalidate_expired`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `invalidate_expired`()
BEGIN 

	UPDATE produto_has_preco 
SET 
    expirado = TRUE
WHERE
    validadeFim < CURDATE();
    
    -- se nao tiver preço valido, marca produto como descontinuado                
	UPDATE produto 
SET 
    descontinuado = TRUE
WHERE
    idProduto NOT IN (SELECT 
            idProduto
        FROM
            produto_has_preco
        WHERE
            expirado = FALSE)
        AND descontinuado = FALSE;

-- copia o preço valido para produto
	UPDATE produto AS p,
    produto_has_preco AS prc 
SET 
    p.precovenda = prc.preco
WHERE
    p.idProduto = prc.idProduto
        AND prc.expirado = FALSE
        AND p.descontinuado = FALSE;
        
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure update_venda_status
-- -----------------------------------------------------

USE `mydb`;
DROP procedure IF EXISTS `mydb`.`update_venda_status`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `update_venda_status`()
BEGIN 

	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'ESTOQUE';
	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'EM RECEBIMENTO';
	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'EM COLETA';
	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'EM FATURAMENTO';
	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'EM COMPRA';
	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'INICIADO';
    UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'PENDENTE';
        
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`view_estoque`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_estoque` ;
DROP TABLE IF EXISTS `mydb`.`view_estoque`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_estoque` AS
    SELECT 
        `p`.`fornecedor` AS `Fornecedor`,
        `e`.`descricao` AS `Produto`,
        SUM(`e`.`quant`) AS `Quant`,
        `e`.`codComercial` AS `Cód Com`,
        `e`.`status` AS `Status`
    FROM
        (`mydb`.`estoque` `e`
        LEFT JOIN `mydb`.`produto` `p` ON ((`e`.`codComercial` = `p`.`codComercial`)))
    GROUP BY `e`.`descricao`;

-- -----------------------------------------------------
-- View `mydb`.`view_orcamento`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_orcamento` ;
DROP TABLE IF EXISTS `mydb`.`view_orcamento`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_orcamento` AS
    SELECT 
        `mydb`.`orcamento`.`idOrcamento` AS `Código`,
        `mydb`.`cliente`.`nome_razao` AS `Cliente`,
        `mydb`.`orcamento`.`total` AS `Total`,
        `mydb`.`orcamento`.`data` AS `Data de emissão`,
        `mydb`.`orcamento`.`status` AS `Status`,
        (`mydb`.`orcamento`.`validade` - (TO_DAYS(NOW()) - TO_DAYS(`mydb`.`orcamento`.`data`))) AS `Dias restantes`
    FROM
        (`mydb`.`orcamento`
        LEFT JOIN `mydb`.`cliente` ON ((`mydb`.`orcamento`.`idCliente` = `mydb`.`cliente`.`idCliente`)));

-- -----------------------------------------------------
-- View `mydb`.`view_venda`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_venda` ;
DROP TABLE IF EXISTS `mydb`.`view_venda`;
USE `mydb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `mydb`.`view_venda` AS select `v`.`idVenda` AS `idVenda`,`l`.`descricao` AS `Loja`,`u`.`nome` AS `Vendedor`,`c`.`nome_razao` AS `Cliente`,`e`.`logradouro` AS `Endereço`,`p`.`nome_razao` AS `Profissional`,`v`.`data` AS `Data`,`v`.`subTotalBru` AS `Bruto`,`v`.`subTotalLiq` AS `Líquido`,`v`.`frete` AS `Frete`,`v`.`total` AS `Total R$`,`v`.`status` AS `Status`,(to_days(`v`.`prazoEntrega`) - to_days(now())) AS `Dias restantes` from (((((`mydb`.`venda` `v` left join `mydb`.`loja` `l` on((`v`.`idLoja` = `l`.`idLoja`))) left join `mydb`.`usuario` `u` on((`v`.`idUsuario` = `u`.`idUsuario`))) left join `mydb`.`cliente_has_endereco` `e` on((`v`.`idEnderecoEntrega` = `e`.`idEndereco`))) left join `mydb`.`profissional` `p` on((`v`.`idProfissional` = `p`.`idProfissional`))) left join `mydb`.`cliente` `c` on((`v`.`idCliente` = `c`.`idCliente`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`loja`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`loja` (`idLoja`, `descricao`, `nomeFantasia`, `razaoSocial`, `tel`, `tel2`, `inscEstadual`, `sigla`, `cnpj`, `codUF`, `porcentagemFrete`, `valorMinimoFrete`, `servidorACBr`, `portaACBr`, `pastaEntACBr`, `pastaSaiACBr`, `pastaXmlACBr`, `servidorSMTP`, `portaSMTP`, `emailCompra`, `emailSenha`, `pastaCompra`, `desativado`) VALUES (1, 'Alphaville', 'Staccato', 'STACCATO REVESTIMENTOS COMÉRCIO E REPRESENTAÇÃO LTDA', '(11)4191-9816', NULL, '206.257.840.114', 'ALPH', '09.375.013/0001-10', 35, 4, 80, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL, NULL, NULL, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`alcadas`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`alcadas` (`idAlcada`, `idLoja`, `tipoFuncionario`, `debito`, `credito`, `cheque`, `dinheiro`, `boleto`) VALUES (1, 1, 'Vendedor', 4, 2, 4, 5, 5);
INSERT INTO `mydb`.`alcadas` (`idAlcada`, `idLoja`, `tipoFuncionario`, `debito`, `credito`, `cheque`, `dinheiro`, `boleto`) VALUES (2, 1, 'Gerente', 8, 4, 8, 10, 10);
INSERT INTO `mydb`.`alcadas` (`idAlcada`, `idLoja`, `tipoFuncionario`, `debito`, `credito`, `cheque`, `dinheiro`, `boleto`) VALUES (3, 1, 'Administrador', 16, 8, 16, 20, 20);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`profissional`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`profissional` (`idProfissional`, `pfpj`, `nome_razao`, `nomeFantasia`, `cpf`, `cnpj`, `rg`, `inscEstadual`, `contatoNome`, `contatoCPF`, `contatoApelido`, `contatoRG`, `tel`, `telCel`, `telCom`, `idNextel`, `nextel`, `email`, `tipoProf`, `banco`, `agencia`, `cc`, `nomeBanco`, `cpfBanco`, `incompleto`, `desativado`) VALUES (1, NULL, 'Não há', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`usuario` (`idUsuario`, `idLoja`, `user`, `passwd`, `tipo`, `nome`, `sigla`, `email`, `desativado`) VALUES (1, 1, 'admin', '*A4B6157319038724E3560894F7F932C8886EBFCF', 'ADMINISTRADOR', 'Administrador', 'ADM', NULL, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`cliente`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`cliente` (`idCliente`, `pfpj`, `nome_razao`, `nomeFantasia`, `cpf`, `cnpj`, `rg`, `dataNasc`, `inscEstadual`, `contatoNome`, `contatoCPF`, `contatoApelido`, `contatoRG`, `tel`, `telCel`, `telCom`, `idNextel`, `nextel`, `email`, `idUsuarioRel`, `idCadastroRel`, `idProfissionalRel`, `incompleto`, `desativado`) VALUES (1, 'PJ', 'Eduardo Pinto de Oliveira', NULL, NULL, '11.111.111/1111-11', NULL, NULL, 'ISENTO', NULL, NULL, NULL, NULL, '(11)4153-0948', NULL, NULL, NULL, NULL, 'edu.oliv@globo.com', NULL, NULL, NULL, 0, DEFAULT);
INSERT INTO `mydb`.`cliente` (`idCliente`, `pfpj`, `nome_razao`, `nomeFantasia`, `cpf`, `cnpj`, `rg`, `dataNasc`, `inscEstadual`, `contatoNome`, `contatoCPF`, `contatoApelido`, `contatoRG`, `tel`, `telCel`, `telCom`, `idNextel`, `nextel`, `email`, `idUsuarioRel`, `idCadastroRel`, `idProfissionalRel`, `incompleto`, `desativado`) VALUES (2, 'PF', 'Rodrigo Torres Alves', NULL, '927.636.342-49', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`cliente_has_endereco`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`cliente_has_endereco` (`idEndereco`, `idCliente`, `descricao`, `cep`, `logradouro`, `numero`, `complemento`, `bairro`, `cidade`, `uf`, `codUF`, `desativado`) VALUES (1, NULL, 'Não há/Retira', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DEFAULT);
INSERT INTO `mydb`.`cliente_has_endereco` (`idEndereco`, `idCliente`, `descricao`, `cep`, `logradouro`, `numero`, `complemento`, `bairro`, `cidade`, `uf`, `codUF`, `desativado`) VALUES (2, 1, 'RESIDENCIA', '06543-260', 'Rua Cerejeira', '956', NULL, 'Condomínio Melville (Tamboré)', 'Santana de Parnaíba', 'SP', 35, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`loja_has_endereco`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`loja_has_endereco` (`idEndereco`, `idLoja`, `descricao`, `cep`, `logradouro`, `numero`, `complemento`, `bairro`, `cidade`, `uf`, `codUF`, `desativado`) VALUES (1, 1, 'Principal', '06473-000', 'Avenida Andrômeda', '900', NULL, 'Alphaville Empresarial', 'Barueri', 'SP', 35, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`profissional_has_endereco`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`profissional_has_endereco` (`idEndereco`, `idProfissional`, `descricao`, `cep`, `logradouro`, `numero`, `complemento`, `bairro`, `cidade`, `uf`, `codUF`, `desativado`) VALUES (1, NULL, 'Não há', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, DEFAULT);

COMMIT;

