-- MySQL Script generated by MySQL Workbench
-- 08/07/16 23:54:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`loja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`loja` ;

CREATE TABLE IF NOT EXISTS `mydb`.`loja` (
  `idLoja` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `nomeFantasia` VARCHAR(45) NOT NULL,
  `razaoSocial` VARCHAR(60) NOT NULL,
  `tel` VARCHAR(18) NOT NULL,
  `tel2` VARCHAR(18) NULL DEFAULT NULL,
  `inscEstadual` VARCHAR(20) NOT NULL,
  `sigla` VARCHAR(4) NOT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `codUF` INT(11) NOT NULL DEFAULT '0',
  `porcentagemFrete` INT(11) NOT NULL DEFAULT '4',
  `valorMinimoFrete` INT(11) NOT NULL DEFAULT '80',
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idLoja`),
  UNIQUE INDEX `idLoja_UNIQUE` (`idLoja` ASC),
  FULLTEXT INDEX `idxFT` (`descricao` ASC, `nomeFantasia` ASC, `razaoSocial` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`alcadas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alcadas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alcadas` (
  `idAlcada` INT(11) NOT NULL AUTO_INCREMENT,
  `idLoja` INT(10) UNSIGNED NOT NULL,
  `tipoFuncionario` VARCHAR(45) NOT NULL DEFAULT '',
  `debito` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `credito` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `cheque` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `dinheiro` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `boleto` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idAlcada`),
  UNIQUE INDEX `idAlcada_UNIQUE` (`idAlcada` ASC),
  INDEX `fk_Alçadas_Loja1_idx` (`idLoja` ASC),
  CONSTRAINT `fk_Alçadas_Loja`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`profissional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profissional` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profissional` (
  `idProfissional` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idLoja` INT(10) NULL DEFAULT NULL,
  `idUsuarioRel` INT(10) NULL DEFAULT NULL,
  `pfpj` VARCHAR(45) NULL DEFAULT NULL,
  `nome_razao` VARCHAR(45) NOT NULL,
  `nomeFantasia` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `cnpj` VARCHAR(18) NULL DEFAULT NULL,
  `inscEstadual` VARCHAR(45) NULL DEFAULT NULL,
  `contatoNome` VARCHAR(45) NULL DEFAULT NULL,
  `contatoCPF` VARCHAR(45) NULL DEFAULT NULL,
  `contatoApelido` VARCHAR(45) NULL DEFAULT NULL,
  `contatoRG` VARCHAR(45) NULL DEFAULT NULL,
  `tel` VARCHAR(45) NULL DEFAULT NULL,
  `telCel` VARCHAR(18) NULL DEFAULT NULL,
  `telCom` VARCHAR(18) NULL DEFAULT NULL,
  `idNextel` VARCHAR(16) NULL DEFAULT NULL,
  `nextel` VARCHAR(18) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `tipoProf` VARCHAR(45) NULL DEFAULT NULL,
  `banco` VARCHAR(45) NULL DEFAULT NULL,
  `agencia` VARCHAR(45) NULL DEFAULT NULL,
  `cc` VARCHAR(45) NULL DEFAULT NULL,
  `nomeBanco` VARCHAR(45) NULL DEFAULT NULL,
  `cpfBanco` VARCHAR(45) NULL DEFAULT NULL,
  `comissao` DECIMAL(15,4) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idProfissional`),
  FULLTEXT INDEX `idxFT` (`nome_razao` ASC, `tipoProf` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 695
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idUsuario` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idLoja` INT(10) UNSIGNED NOT NULL,
  `user` VARCHAR(20) NOT NULL,
  `passwd` VARCHAR(42) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC),
  INDEX `fk_Usuario_Loja1_idx` (`idLoja` ASC),
  FULLTEXT INDEX `idxFT` (`nome` ASC, `tipo` ASC),
  CONSTRAINT `fk_Usuario_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idCliente` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `pfpj` VARCHAR(45) NOT NULL,
  `nome_razao` VARCHAR(45) NOT NULL,
  `nomeFantasia` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `cnpj` VARCHAR(18) NULL DEFAULT NULL,
  `dataNasc` DATE NULL DEFAULT NULL,
  `inscEstadual` VARCHAR(45) NULL DEFAULT NULL,
  `contatoNome` VARCHAR(45) NULL DEFAULT NULL,
  `contatoCPF` VARCHAR(45) NULL DEFAULT NULL,
  `contatoApelido` VARCHAR(45) NULL DEFAULT NULL,
  `contatoRG` VARCHAR(45) NULL DEFAULT NULL,
  `tel` VARCHAR(18) NULL DEFAULT NULL,
  `telCel` VARCHAR(18) NULL DEFAULT NULL,
  `telCom` VARCHAR(18) NULL DEFAULT NULL,
  `idNextel` VARCHAR(16) NULL DEFAULT NULL,
  `nextel` VARCHAR(18) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `idUsuarioRel` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idCadastroRel` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idProfissionalRel` INT(10) UNSIGNED NULL DEFAULT NULL,
  `credito` DECIMAL(15,4) NULL DEFAULT NULL,
  `incompleto` TINYINT(1) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Usuario1_idx` (`idUsuarioRel` ASC),
  INDEX `fk_Cliente_Cliente1_idx` (`idCadastroRel` ASC),
  INDEX `fk_Cliente_Profissional1_idx` (`idProfissionalRel` ASC),
  INDEX `fk_Cadastro_Produto_idx` (`idCliente` ASC),
  FULLTEXT INDEX `idxFT` (`nome_razao` ASC, `nomeFantasia` ASC, `cpf` ASC, `cnpj` ASC),
  CONSTRAINT `fk_Cliente_Cliente1`
    FOREIGN KEY (`idCadastroRel`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Profissional1`
    FOREIGN KEY (`idProfissionalRel`)
    REFERENCES `mydb`.`profissional` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Usuario1`
    FOREIGN KEY (`idUsuarioRel`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3582
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cliente_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cliente_has_endereco` (
  `idEndereco` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idCliente` INT(10) UNSIGNED NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `logradouro` VARCHAR(90) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(72) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `uf` VARCHAR(45) NULL DEFAULT NULL,
  `codUF` INT(11) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Cliente_has_Endereco_Cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_Cliente_has_Endereco_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2217
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`conta_a_pagar_has_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta_a_pagar_has_pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta_a_pagar_has_pagamento` (
  `idPagamento` INT(11) NOT NULL AUTO_INCREMENT,
  `dataEmissao` DATE NULL DEFAULT NULL,
  `idCompra` INT(11) NOT NULL,
  `idLoja` INT(10) UNSIGNED NOT NULL,
  `dataPagamento` DATE NULL DEFAULT NULL,
  `valor` DECIMAL(15,4) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `parcela` INT(11) NOT NULL,
  `observacao` VARCHAR(200) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDENTE',
  `dataRealizado` DATE NULL DEFAULT NULL,
  `valorReal` DECIMAL(15,4) NULL DEFAULT NULL,
  `tipoReal` VARCHAR(45) NULL DEFAULT NULL,
  `parcelaReal` INT(11) NULL DEFAULT NULL,
  `contaDestino` VARCHAR(45) NULL DEFAULT NULL,
  `tipoDet` VARCHAR(45) NULL DEFAULT NULL,
  `centroCusto` VARCHAR(45) NULL DEFAULT NULL,
  `grupo` VARCHAR(45) NULL DEFAULT NULL,
  `subGrupo` VARCHAR(45) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idPagamento`),
  UNIQUE INDEX `idPagamento_UNIQUE` (`idPagamento` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1806
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `idVenda` VARCHAR(30) NOT NULL,
  `idOrcamento` VARCHAR(30) NOT NULL,
  `idLoja` INT(10) UNSIGNED NOT NULL,
  `idUsuario` INT(10) UNSIGNED NOT NULL,
  `idUsuarioIndicou` INT(10) NULL DEFAULT NULL,
  `idCliente` INT(10) UNSIGNED NOT NULL,
  `idEnderecoEntrega` INT(10) UNSIGNED NOT NULL,
  `idEnderecoFaturamento` INT(10) UNSIGNED NOT NULL,
  `idProfissional` INT(10) UNSIGNED NOT NULL,
  `data` DATETIME NOT NULL,
  `dataOrc` DATETIME NOT NULL,
  `subTotalBru` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `subTotalLiq` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `frete` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `descontoPorc` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `descontoReais` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `total` DECIMAL(15,4) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'ATIVO',
  `statusEntrega` VARCHAR(45) NULL DEFAULT NULL,
  `observacao` VARCHAR(3000) NULL DEFAULT NULL,
  `prazoEntrega` INT(11) NOT NULL,
  `representacao` TINYINT(1) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idVenda`),
  UNIQUE INDEX `idVenda_UNIQUE` (`idVenda` ASC),
  INDEX `fk_Venda_Cliente1_idx` (`idCliente` ASC),
  INDEX `fk_Venda_Loja1_idx` (`idLoja` ASC),
  INDEX `fk_Venda_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Venda_Profissional1_idx` (`idProfissional` ASC),
  INDEX `fk_Venda_Endereco1_idx` (`idEnderecoEntrega` ASC),
  INDEX `fk_Venda_Endereco2_idx` (`idEnderecoFaturamento` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Endereco1`
    FOREIGN KEY (`idEnderecoEntrega`)
    REFERENCES `mydb`.`cliente_has_endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Endereco2`
    FOREIGN KEY (`idEnderecoFaturamento`)
    REFERENCES `mydb`.`cliente_has_endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Profissional1`
    FOREIGN KEY (`idProfissional`)
    REFERENCES `mydb`.`profissional` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`conta_a_receber_has_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`conta_a_receber_has_pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`conta_a_receber_has_pagamento` (
  `idPagamento` INT(11) NOT NULL AUTO_INCREMENT,
  `dataEmissao` DATE NULL DEFAULT NULL,
  `idVenda` VARCHAR(30) NOT NULL,
  `idLoja` INT(10) UNSIGNED NOT NULL,
  `valor` DECIMAL(15,4) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `parcela` INT(11) NOT NULL,
  `dataPagamento` DATE NULL DEFAULT NULL,
  `observacao` VARCHAR(200) NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDENTE',
  `representacao` TINYINT(1) NOT NULL DEFAULT '0',
  `dataRealizado` DATE NULL DEFAULT NULL,
  `valorReal` DECIMAL(15,4) NULL DEFAULT NULL,
  `tipoReal` VARCHAR(45) NULL DEFAULT NULL,
  `parcelaReal` INT(11) NULL DEFAULT NULL,
  `contaDestino` VARCHAR(45) NULL DEFAULT NULL,
  `tipoDet` VARCHAR(45) NULL DEFAULT NULL,
  `centroCusto` VARCHAR(45) NULL DEFAULT NULL,
  `grupo` VARCHAR(45) NULL DEFAULT NULL,
  `subGrupo` VARCHAR(45) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idPagamento`),
  UNIQUE INDEX `idPagamento_UNIQUE` (`idPagamento` ASC),
  INDEX `fk_Conta_Venda_idx` (`idVenda` ASC),
  CONSTRAINT `fk_Conta_Venda2`
    FOREIGN KEY (`idVenda`)
    REFERENCES `mydb`.`venda` (`idVenda`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6416
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estoque` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `idEstoque` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL DEFAULT 'TEMP',
  `ordemCompra` INT(11) NULL DEFAULT NULL,
  `numeroNFe` INT(11) NULL DEFAULT NULL,
  `idNFe` VARCHAR(45) NULL DEFAULT NULL,
  `idCompra` VARCHAR(45) NOT NULL DEFAULT '0',
  `local` VARCHAR(100) NULL DEFAULT 'TEMP',
  `idProduto` INT(11) NULL DEFAULT NULL,
  `fornecedor` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `quant` DECIMAL(15,4) NULL DEFAULT NULL,
  `quantUpd` INT(11) NOT NULL DEFAULT '0',
  `un` VARCHAR(45) NULL DEFAULT NULL,
  `caixas` INT(11) NULL DEFAULT NULL,
  `codBarras` VARCHAR(45) NULL DEFAULT NULL,
  `codComercial` VARCHAR(45) NULL DEFAULT NULL,
  `ncm` VARCHAR(45) NULL DEFAULT NULL,
  `cfop` VARCHAR(45) NULL DEFAULT NULL,
  `valorUnid` DECIMAL(15,4) NULL DEFAULT NULL,
  `valor` DECIMAL(15,4) NULL DEFAULT NULL,
  `codBarrasTrib` VARCHAR(45) NULL DEFAULT NULL,
  `unTrib` VARCHAR(45) NULL DEFAULT NULL,
  `quantTrib` DECIMAL(15,4) NULL DEFAULT NULL,
  `valorTrib` DECIMAL(15,4) NULL DEFAULT NULL,
  `desconto` DECIMAL(15,4) NULL DEFAULT NULL,
  `compoeTotal` INT(11) NULL DEFAULT NULL,
  `numeroPedido` VARCHAR(45) NULL DEFAULT NULL,
  `itemPedido` INT(11) NULL DEFAULT NULL,
  `tipoICMS` VARCHAR(45) NULL DEFAULT NULL,
  `orig` DECIMAL(15,4) NULL DEFAULT NULL,
  `cstICMS` DECIMAL(15,4) NULL DEFAULT NULL,
  `modBC` DECIMAL(15,4) NULL DEFAULT NULL,
  `vBC` DECIMAL(15,4) NULL DEFAULT NULL,
  `pICMS` DECIMAL(15,4) NULL DEFAULT NULL,
  `vICMS` DECIMAL(15,4) NULL DEFAULT NULL,
  `modBCST` DECIMAL(15,4) NULL DEFAULT NULL,
  `pMVAST` DECIMAL(15,4) NULL DEFAULT NULL,
  `vBCST` DECIMAL(15,4) NULL DEFAULT NULL,
  `pICMSST` DECIMAL(15,4) NULL DEFAULT NULL,
  `vICMSST` DECIMAL(15,4) NULL DEFAULT NULL,
  `cEnq` DECIMAL(15,4) NULL DEFAULT NULL,
  `cstIPI` DECIMAL(15,4) NULL DEFAULT NULL,
  `cstPIS` DECIMAL(15,4) NULL DEFAULT NULL,
  `vBCPIS` DECIMAL(15,4) NULL DEFAULT NULL,
  `pPIS` DECIMAL(15,4) NULL DEFAULT NULL,
  `vPIS` DECIMAL(15,4) NULL DEFAULT NULL,
  `cstCOFINS` DECIMAL(15,4) NULL DEFAULT NULL,
  `vBCCOFINS` DECIMAL(15,4) NULL DEFAULT NULL,
  `pCOFINS` DECIMAL(15,4) NULL DEFAULT NULL,
  `vCOFINS` DECIMAL(15,4) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idEstoque`),
  UNIQUE INDEX `idEstoque_UNIQUE` (`idEstoque` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3207
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_fornecedor_has_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido_fornecedor_has_produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido_fornecedor_has_produto` (
  `idPedido` INT(11) NOT NULL AUTO_INCREMENT,
  `selecionado` TINYINT(1) NULL DEFAULT '0',
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDENTE',
  `ordemCompra` INT(11) NULL DEFAULT NULL,
  `idVenda` VARCHAR(30) NULL DEFAULT NULL,
  `idCompra` INT(11) NULL DEFAULT NULL,
  `idNFe` VARCHAR(45) NULL DEFAULT NULL,
  `idEstoque` VARCHAR(45) NULL DEFAULT NULL,
  `fornecedor` VARCHAR(45) NOT NULL,
  `idProduto` INT(11) NULL DEFAULT NULL,
  `descricao` VARCHAR(200) NULL DEFAULT NULL,
  `colecao` VARCHAR(45) NULL DEFAULT NULL,
  `codComercial` VARCHAR(45) NULL DEFAULT NULL,
  `quant` DECIMAL(15,4) NULL DEFAULT NULL,
  `quantUpd` INT(11) NOT NULL DEFAULT '0',
  `quantConsumida` DECIMAL(15,4) NULL DEFAULT NULL,
  `un` VARCHAR(45) NULL DEFAULT NULL,
  `un2` VARCHAR(45) NULL DEFAULT NULL,
  `caixas` INT(11) NULL DEFAULT NULL,
  `prcUnitario` DECIMAL(15,4) NULL DEFAULT NULL,
  `preco` DECIMAL(15,4) NULL DEFAULT NULL,
  `kgcx` DECIMAL(15,4) NULL DEFAULT NULL,
  `formComercial` VARCHAR(45) NULL DEFAULT NULL,
  `codBarras` VARCHAR(45) NULL DEFAULT NULL,
  `obs` VARCHAR(200) NULL DEFAULT NULL,
  `dataPrevCompra` DATE NULL DEFAULT NULL,
  `dataRealCompra` DATE NULL DEFAULT NULL,
  `dataPrevConf` DATE NULL DEFAULT NULL,
  `dataRealConf` DATE NULL DEFAULT NULL,
  `dataPrevFat` DATE NULL DEFAULT NULL,
  `dataRealFat` DATE NULL DEFAULT NULL,
  `dataPrevColeta` DATE NULL DEFAULT NULL,
  `dataRealColeta` DATE NULL DEFAULT NULL,
  `dataPrevReceb` DATE NULL DEFAULT NULL,
  `dataRealReceb` DATE NULL DEFAULT NULL,
  `dataPrevEnt` DATE NULL DEFAULT NULL,
  `dataRealEnt` DATE NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idPedido`),
  INDEX `idCompra` (`idCompra` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 4971
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`estoque_has_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estoque_has_compra` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estoque_has_compra` (
  `idEstoque` INT(11) NOT NULL,
  `idCompra` INT(11) NOT NULL,
  PRIMARY KEY (`idEstoque`, `idCompra`),
  INDEX `idCompra_idx` (`idCompra` ASC),
  CONSTRAINT `fk_estoquecompra_estoque`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `mydb`.`estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoquecompra_pedido`
    FOREIGN KEY (`idCompra`)
    REFERENCES `mydb`.`pedido_fornecedor_has_produto` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `idFornecedor` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(45) NOT NULL,
  `nomeFantasia` VARCHAR(45) NULL DEFAULT NULL,
  `cnpj` VARCHAR(18) NULL DEFAULT NULL,
  `inscEstadual` VARCHAR(45) NULL DEFAULT NULL,
  `contatoNome` VARCHAR(45) NULL DEFAULT NULL,
  `contatoCPF` VARCHAR(45) NULL DEFAULT NULL,
  `contatoApelido` VARCHAR(45) NULL DEFAULT NULL,
  `contatoRG` VARCHAR(45) NULL DEFAULT NULL,
  `tel` VARCHAR(18) NULL DEFAULT NULL,
  `telCel` VARCHAR(18) NULL DEFAULT NULL,
  `telCom` VARCHAR(18) NULL DEFAULT NULL,
  `idNextel` VARCHAR(16) NULL DEFAULT NULL,
  `nextel` VARCHAR(18) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `comissao1` DOUBLE NULL DEFAULT NULL,
  `comissao2` DOUBLE NULL DEFAULT NULL,
  `comissaoLoja` DOUBLE NULL DEFAULT NULL,
  `idUsuarioRel` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idCadastroRel` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idProfissionalRel` INT(10) UNSIGNED NULL DEFAULT NULL,
  `representacao` TINYINT(1) NULL DEFAULT NULL,
  `coleta` TINYINT(1) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idFornecedor`),
  INDEX `fk_Fornecedor_Usuario1_idx` (`idUsuarioRel` ASC),
  INDEX `fk_Fornecedor_Fornecedor1_idx` (`idCadastroRel` ASC),
  INDEX `fk_Fornecedor_Profissional1_idx` (`idProfissionalRel` ASC),
  FULLTEXT INDEX `idxFT` (`razaoSocial` ASC, `nomeFantasia` ASC, `cnpj` ASC),
  CONSTRAINT `fk_Fornecedor_Fornecedor1`
    FOREIGN KEY (`idCadastroRel`)
    REFERENCES `mydb`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_Profissional1`
    FOREIGN KEY (`idProfissionalRel`)
    REFERENCES `mydb`.`profissional` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fornecedor_Usuario1`
    FOREIGN KEY (`idUsuarioRel`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 142
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `idProduto` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idProdutoUpd` INT(11) NOT NULL DEFAULT '0',
  `idFornecedor` INT(10) UNSIGNED NOT NULL,
  `idFornecedorUpd` INT(11) NOT NULL DEFAULT '0',
  `fornecedor` VARCHAR(100) NOT NULL,
  `fornecedorUpd` INT(11) NOT NULL DEFAULT '0',
  `descricao` VARCHAR(250) NOT NULL,
  `descricaoUpd` INT(11) NOT NULL DEFAULT '0',
  `estoque` INT(11) NOT NULL DEFAULT '0',
  `estoqueUpd` INT(11) NOT NULL DEFAULT '0',
  `un` VARCHAR(10) NOT NULL,
  `unUpd` INT(11) NOT NULL DEFAULT '0',
  `un2` VARCHAR(10) NULL DEFAULT NULL,
  `un2Upd` INT(11) NULL DEFAULT '0',
  `colecao` VARCHAR(100) NULL DEFAULT NULL,
  `colecaoUpd` INT(11) NOT NULL DEFAULT '0',
  `tipo` VARCHAR(100) NULL DEFAULT NULL,
  `tipoUpd` INT(11) NOT NULL DEFAULT '0',
  `minimo` DOUBLE NULL DEFAULT NULL,
  `minimoUpd` INT(11) NOT NULL DEFAULT '0',
  `multiplo` DOUBLE NULL DEFAULT NULL,
  `multiploUpd` INT(11) NULL DEFAULT NULL,
  `m2cx` DECIMAL(15,4) NULL DEFAULT NULL,
  `m2cxUpd` INT(11) NOT NULL DEFAULT '0',
  `pccx` DECIMAL(15,4) NULL DEFAULT NULL,
  `pccxUpd` INT(11) NOT NULL DEFAULT '0',
  `kgcx` DECIMAL(15,4) NULL DEFAULT NULL,
  `kgcxUpd` INT(11) NOT NULL DEFAULT '0',
  `formComercial` VARCHAR(100) NULL DEFAULT NULL,
  `formComercialUpd` INT(11) NOT NULL DEFAULT '0',
  `codComercial` VARCHAR(100) NOT NULL,
  `codComercialUpd` INT(11) NOT NULL DEFAULT '0',
  `codBarras` VARCHAR(100) NULL DEFAULT '0',
  `codBarrasUpd` INT(11) NOT NULL DEFAULT '0',
  `ncm` VARCHAR(10) NULL DEFAULT NULL,
  `ncmUpd` INT(11) NOT NULL DEFAULT '0',
  `ncmEx` VARCHAR(2) NULL DEFAULT NULL,
  `ncmExUpd` INT(11) NOT NULL DEFAULT '0',
  `cfop` VARCHAR(4) NULL DEFAULT NULL,
  `cfopUpd` INT(11) NOT NULL DEFAULT '0',
  `icms` DECIMAL(15,4) NULL DEFAULT NULL,
  `icmsUpd` INT(11) NOT NULL DEFAULT '0',
  `cst` VARCHAR(3) NULL DEFAULT '000',
  `cstUpd` INT(11) NOT NULL DEFAULT '0',
  `qtdPallet` DECIMAL(15,4) NULL DEFAULT NULL,
  `qtdPalletUpd` INT(11) NOT NULL DEFAULT '0',
  `custo` DECIMAL(15,4) NOT NULL,
  `custoUpd` INT(11) NOT NULL DEFAULT '0',
  `ipi` DECIMAL(15,4) NULL DEFAULT NULL,
  `ipiUpd` INT(11) NOT NULL DEFAULT '0',
  `st` DECIMAL(15,4) NULL DEFAULT NULL,
  `stUpd` INT(11) NOT NULL DEFAULT '0',
  `precoVenda` DECIMAL(15,4) NULL DEFAULT NULL,
  `precoVendaUpd` INT(11) NOT NULL DEFAULT '0',
  `markup` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `markupUpd` INT(11) NOT NULL DEFAULT '0',
  `comissao` DECIMAL(15,4) NULL DEFAULT NULL,
  `comissaoUpd` INT(11) NOT NULL DEFAULT '0',
  `observacoes` VARCHAR(800) NULL DEFAULT NULL,
  `observacoesUpd` INT(11) NOT NULL DEFAULT '0',
  `origem` INT(11) NULL DEFAULT NULL,
  `origemUpd` INT(11) NOT NULL DEFAULT '0',
  `temLote` VARCHAR(5) NULL DEFAULT 'NÃO',
  `temLoteUpd` INT(11) NOT NULL DEFAULT '0',
  `ui` VARCHAR(10) NOT NULL DEFAULT '0',
  `uiUpd` INT(11) NOT NULL DEFAULT '0',
  `validade` DATE NULL DEFAULT NULL,
  `validadeUpd` INT(11) NOT NULL DEFAULT '0',
  `descontinuado` TINYINT(1) NOT NULL DEFAULT '0',
  `descontinuadoUpd` INT(11) NOT NULL DEFAULT '0',
  `atualizarTabelaPreco` TINYINT(1) NOT NULL DEFAULT '0',
  `representacao` TINYINT(1) NOT NULL DEFAULT '0',
  `estoque_promocao` INT(2) NULL DEFAULT '0',
  `estoque_promocaoUpd` INT(11) NULL DEFAULT NULL,
  `idProdutoRelacionado` INT(11) NULL DEFAULT NULL,
  `idProdutoRelacionadoUpd` INT(11) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idProduto`),
  UNIQUE INDEX `idProduto_UNIQUE` (`idProduto` ASC),
  INDEX `fk_Produto_Fornecedor1_idx` (`idFornecedor` ASC),
  INDEX `index` (`fornecedor` ASC, `descricao` ASC, `colecao` ASC, `codComercial` ASC, `formComercial` ASC, `ui` ASC),
  INDEX `descontinuado` (`descontinuado` ASC),
  FULLTEXT INDEX `idxFT` (`fornecedor` ASC, `descricao` ASC, `colecao` ASC, `codComercial` ASC),
  CONSTRAINT `fk_Produto_Fornecedor1`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `mydb`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 170844
DEFAULT CHARACTER SET = utf8
COMMENT = '													'
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`venda_has_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`venda_has_produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`venda_has_produto` (
  `idVendaProduto` INT(11) NOT NULL AUTO_INCREMENT,
  `selecionado` TINYINT(1) NULL DEFAULT '0',
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `idNfeSaida` INT(11) NULL DEFAULT NULL,
  `fornecedor` VARCHAR(45) NOT NULL,
  `idVenda` VARCHAR(30) NOT NULL,
  `idLoja` INT(10) UNSIGNED NOT NULL,
  `idProduto` INT(10) UNSIGNED NOT NULL,
  `produto` VARCHAR(150) NULL DEFAULT NULL,
  `obs` VARCHAR(145) NOT NULL,
  `prcUnitario` DECIMAL(15,4) NOT NULL,
  `descUnitario` DECIMAL(15,4) NULL DEFAULT NULL,
  `caixas` INT(11) NOT NULL,
  `quant` DECIMAL(15,4) NOT NULL,
  `un` VARCHAR(45) NOT NULL,
  `unCaixa` DECIMAL(15,4) NOT NULL,
  `codComercial` VARCHAR(100) NOT NULL,
  `formComercial` VARCHAR(100) NOT NULL,
  `parcial` DECIMAL(15,4) NOT NULL,
  `desconto` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `parcialDesc` DECIMAL(15,4) NOT NULL,
  `descGlobal` DECIMAL(15,4) NOT NULL,
  `total` DECIMAL(15,4) NOT NULL,
  `idCompra` INT(11) NULL DEFAULT NULL,
  `estoque_promocao` INT(2) NULL DEFAULT NULL,
  `dataPrevCompra` DATE NULL DEFAULT NULL,
  `dataRealCompra` DATE NULL DEFAULT NULL,
  `dataPrevConf` DATE NULL DEFAULT NULL,
  `dataRealConf` DATE NULL DEFAULT NULL,
  `dataPrevFat` DATE NULL DEFAULT NULL,
  `dataRealFat` DATE NULL DEFAULT NULL,
  `dataPrevColeta` DATE NULL DEFAULT NULL,
  `dataRealColeta` DATE NULL DEFAULT NULL,
  `dataPrevReceb` DATE NULL DEFAULT NULL,
  `dataRealReceb` DATE NULL DEFAULT NULL,
  `dataPrevEnt` DATE NULL DEFAULT NULL,
  `dataRealEnt` DATE NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idVendaProduto`),
  UNIQUE INDEX `idVendaProduto_UNIQUE` (`idVendaProduto` ASC),
  INDEX `fk_vendaproduto_produto_idx` (`idProduto` ASC),
  INDEX `fk_vendaproduto_venda_idx` (`idVenda` ASC),
  CONSTRAINT `fk_vendaproduto_produto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendaproduto_venda`
    FOREIGN KEY (`idVenda`)
    REFERENCES `mydb`.`venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8249
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`estoque_has_consumo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estoque_has_consumo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estoque_has_consumo` (
  `idConsumo` INT(11) NOT NULL AUTO_INCREMENT,
  `idEstoque` INT(11) NOT NULL,
  `idVendaProduto` INT(11) NOT NULL DEFAULT '0',
  `status` VARCHAR(45) NULL DEFAULT 'TEMP',
  `ordemCompra` INT(11) NULL DEFAULT NULL,
  `numeroNFe` INT(11) NULL DEFAULT NULL,
  `idNFe` VARCHAR(45) NULL DEFAULT NULL,
  `idCompra` VARCHAR(45) NOT NULL DEFAULT '0',
  `local` VARCHAR(100) NULL DEFAULT 'TEMP',
  `idProduto` INT(11) NULL DEFAULT NULL,
  `fornecedor` VARCHAR(100) NULL DEFAULT NULL,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `quant` DECIMAL(15,4) NULL DEFAULT NULL,
  `quantUpd` INT(11) NOT NULL DEFAULT '0',
  `un` VARCHAR(45) NULL DEFAULT NULL,
  `caixas` INT(11) NULL DEFAULT NULL,
  `codBarras` VARCHAR(45) NULL DEFAULT NULL,
  `codComercial` VARCHAR(45) NULL DEFAULT NULL,
  `ncm` VARCHAR(45) NULL DEFAULT NULL,
  `cfop` VARCHAR(45) NULL DEFAULT NULL,
  `valorUnid` DECIMAL(15,4) NULL DEFAULT NULL,
  `valor` DECIMAL(15,4) NULL DEFAULT NULL,
  `codBarrasTrib` VARCHAR(45) NULL DEFAULT NULL,
  `unTrib` VARCHAR(45) NULL DEFAULT NULL,
  `quantTrib` DECIMAL(15,4) NULL DEFAULT NULL,
  `valorTrib` DECIMAL(15,4) NULL DEFAULT NULL,
  `desconto` DECIMAL(15,4) NULL DEFAULT NULL,
  `compoeTotal` INT(11) NULL DEFAULT NULL,
  `numeroPedido` VARCHAR(45) NULL DEFAULT NULL,
  `itemPedido` INT(11) NULL DEFAULT NULL,
  `tipoICMS` VARCHAR(45) NULL DEFAULT NULL,
  `orig` DECIMAL(15,4) NULL DEFAULT NULL,
  `cstICMS` DECIMAL(15,4) NULL DEFAULT NULL,
  `modBC` DECIMAL(15,4) NULL DEFAULT NULL,
  `vBC` DECIMAL(15,4) NULL DEFAULT NULL,
  `pICMS` DECIMAL(15,4) NULL DEFAULT NULL,
  `vICMS` DECIMAL(15,4) NULL DEFAULT NULL,
  `modBCST` DECIMAL(15,4) NULL DEFAULT NULL,
  `pMVAST` DECIMAL(15,4) NULL DEFAULT NULL,
  `vBCST` DECIMAL(15,4) NULL DEFAULT NULL,
  `pICMSST` DECIMAL(15,4) NULL DEFAULT NULL,
  `vICMSST` DECIMAL(15,4) NULL DEFAULT NULL,
  `cEnq` DECIMAL(15,4) NULL DEFAULT NULL,
  `cstIPI` DECIMAL(15,4) NULL DEFAULT NULL,
  `cstPIS` DECIMAL(15,4) NULL DEFAULT NULL,
  `vBCPIS` DECIMAL(15,4) NULL DEFAULT NULL,
  `pPIS` DECIMAL(15,4) NULL DEFAULT NULL,
  `vPIS` DECIMAL(15,4) NULL DEFAULT NULL,
  `cstCOFINS` DECIMAL(15,4) NULL DEFAULT NULL,
  `vBCCOFINS` DECIMAL(15,4) NULL DEFAULT NULL,
  `pCOFINS` DECIMAL(15,4) NULL DEFAULT NULL,
  `vCOFINS` DECIMAL(15,4) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idConsumo`),
  UNIQUE INDEX `idConsumo_UNIQUE` (`idConsumo` ASC),
  INDEX `estoqueconsumo_produto_idx` (`idVendaProduto` ASC),
  INDEX `estoqueconsumo_estoque_idx` (`idEstoque` ASC),
  CONSTRAINT `estoqueconsumo_estoque`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `mydb`.`estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estoqueconsumo_produto`
    FOREIGN KEY (`idVendaProduto`)
    REFERENCES `mydb`.`venda_has_produto` (`idVendaProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3985
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`nfe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`nfe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`nfe` (
  `idNFe` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `numeroNFe` INT(11) NULL DEFAULT NULL,
  `idCompra` VARCHAR(30) NULL DEFAULT NULL,
  `idVenda` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `xml` MEDIUMTEXT NULL DEFAULT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'PENDENTE',
  `chaveAcesso` VARCHAR(50) NOT NULL,
  `obs` VARCHAR(500) NULL DEFAULT NULL,
  `transportadora` VARCHAR(100) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idNFe`))
ENGINE = InnoDB
AUTO_INCREMENT = 2151
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`estoque_has_nfe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estoque_has_nfe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estoque_has_nfe` (
  `idEstoque` INT(11) NOT NULL,
  `idNFe` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idEstoque`, `idNFe`),
  INDEX `idNFe_idx` (`idNFe` ASC),
  CONSTRAINT `estoque_nfe_estoque`
    FOREIGN KEY (`idEstoque`)
    REFERENCES `mydb`.`estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `estoque_nfe_nfe`
    FOREIGN KEY (`idNFe`)
    REFERENCES `mydb`.`nfe` (`idNFe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`fornecedor_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor_has_endereco` (
  `idEndereco` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idFornecedor` INT(10) UNSIGNED NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `logradouro` VARCHAR(90) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(72) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `uf` VARCHAR(45) NULL DEFAULT NULL,
  `codUF` INT(11) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Fornecedor_has_Endereco_Fornecedor1_idx` (`idFornecedor` ASC),
  CONSTRAINT `fk_Fornecedor_has_Endereco_Fornecedor1`
    FOREIGN KEY (`idFornecedor`)
    REFERENCES `mydb`.`fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`loja_has_conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`loja_has_conta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`loja_has_conta` (
  `idConta` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idLoja` INT(10) UNSIGNED NULL DEFAULT NULL,
  `banco` VARCHAR(45) NULL DEFAULT NULL,
  `agencia` VARCHAR(45) NULL DEFAULT NULL,
  `conta` VARCHAR(45) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idConta`),
  INDEX `loja_idx` (`idLoja` ASC),
  CONSTRAINT `loja`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`loja_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`loja_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`loja_has_endereco` (
  `idEndereco` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idLoja` INT(10) UNSIGNED NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `logradouro` VARCHAR(90) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(72) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `uf` VARCHAR(45) NULL DEFAULT NULL,
  `codUF` INT(11) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Loja_has_Endereco_Loja1_idx` (`idLoja` ASC),
  CONSTRAINT `fk_Loja_has_Endereco_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`maintenance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`maintenance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`maintenance` (
  `id` INT(11) NOT NULL,
  `lastInvalidated` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`orcamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orcamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orcamento` (
  `idOrcamento` VARCHAR(30) NOT NULL,
  `idLoja` INT(10) UNSIGNED NOT NULL,
  `idUsuario` INT(10) UNSIGNED NOT NULL,
  `idUsuarioIndicou` INT(10) NULL DEFAULT NULL,
  `idCliente` INT(10) UNSIGNED NOT NULL,
  `idEnderecoEntrega` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idEnderecoFaturamento` INT(10) UNSIGNED NULL DEFAULT NULL,
  `idProfissional` INT(10) UNSIGNED NOT NULL,
  `data` DATETIME NOT NULL,
  `subTotalBru` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `subTotalLiq` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `frete` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `freteManual` TINYINT(1) NULL DEFAULT NULL,
  `descontoPorc` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `descontoReais` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `total` DECIMAL(15,4) NOT NULL,
  `validade` INT(11) NOT NULL DEFAULT '7',
  `status` VARCHAR(45) NOT NULL DEFAULT 'ATIVO',
  `motivoCancelamento` VARCHAR(45) NULL DEFAULT NULL,
  `observacaoCancelamento` VARCHAR(200) NULL DEFAULT NULL,
  `observacao` VARCHAR(3000) NULL DEFAULT NULL,
  `prazoEntrega` INT(11) NULL DEFAULT NULL,
  `representacao` TINYINT(1) NULL DEFAULT NULL,
  `replicadoDe` VARCHAR(20) NULL DEFAULT NULL,
  `replicadoEm` VARCHAR(20) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idOrcamento`),
  UNIQUE INDEX `idOrcamento_UNIQUE` (`idOrcamento` ASC),
  INDEX `fk_Orcamento_Cliente1_idx` (`idCliente` ASC),
  INDEX `fk_Orcamento_Loja1_idx` (`idLoja` ASC),
  INDEX `fk_Orcamento_Usuario1_idx` (`idUsuario` ASC),
  INDEX `fk_Orcamento_Profissional1_idx` (`idProfissional` ASC),
  INDEX `index7` (`idOrcamento` ASC, `data` ASC, `total` ASC, `status` ASC, `validade` ASC, `idCliente` ASC, `idUsuario` ASC),
  CONSTRAINT `fk_Orcamento_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orcamento_Loja1`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orcamento_Profissional1`
    FOREIGN KEY (`idProfissional`)
    REFERENCES `mydb`.`profissional` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orcamento_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`orcamento_has_followup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orcamento_has_followup` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orcamento_has_followup` (
  `idFollowup` INT(11) NOT NULL AUTO_INCREMENT,
  `idOrcamento` VARCHAR(30) NOT NULL,
  `idLoja` INT(11) NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  `semaforo` INT(11) NOT NULL,
  `observacao` VARCHAR(300) NOT NULL,
  `dataFollowup` DATETIME NOT NULL,
  `dataProxFollowup` DATETIME NOT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`idFollowup`),
  INDEX `orcamentofollowup_orcamento_idx` (`idOrcamento` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2388
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`orcamento_has_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orcamento_has_produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orcamento_has_produto` (
  `idOrcamentoProduto` INT(11) NOT NULL AUTO_INCREMENT,
  `idOrcamento` VARCHAR(30) NOT NULL,
  `idLoja` INT(10) UNSIGNED NOT NULL,
  `idProduto` INT(10) UNSIGNED NOT NULL,
  `fornecedor` VARCHAR(45) NOT NULL,
  `produto` VARCHAR(150) NULL DEFAULT NULL,
  `obs` VARCHAR(145) NOT NULL,
  `prcUnitario` DECIMAL(15,4) NOT NULL,
  `descUnitario` DECIMAL(15,4) NULL DEFAULT NULL,
  `caixas` INT(11) NOT NULL,
  `quant` DECIMAL(15,4) NOT NULL,
  `un` VARCHAR(45) NOT NULL,
  `unCaixa` DECIMAL(15,4) NOT NULL,
  `codComercial` VARCHAR(100) NOT NULL,
  `formComercial` VARCHAR(100) NOT NULL,
  `parcial` DECIMAL(15,4) NOT NULL,
  `desconto` DECIMAL(15,4) NOT NULL DEFAULT '0.0000',
  `parcialDesc` DECIMAL(15,4) NOT NULL,
  `descGlobal` DECIMAL(15,4) NOT NULL,
  `total` DECIMAL(15,4) NOT NULL,
  `estoque_promocao` INT(2) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idOrcamentoProduto`),
  INDEX `fk_Orcamento_has_Produto_Produto2_idx` (`idProduto` ASC),
  INDEX `fk_Orcamento_has_Produto_Orcamento2_idx` (`idOrcamento` ASC),
  INDEX `fk_Orcamento_has_Produto_Loja2_idx` (`idLoja` ASC),
  CONSTRAINT `fk_orcamentoproduto_loja`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`loja` (`idLoja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orcamentoproduto_orcamento`
    FOREIGN KEY (`idOrcamento`)
    REFERENCES `mydb`.`orcamento` (`idOrcamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orcamentoproduto_produto`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8660
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`transportadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transportadora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transportadora` (
  `idTransportadora` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `razaoSocial` VARCHAR(60) NOT NULL,
  `nomeFantasia` VARCHAR(45) NULL DEFAULT NULL,
  `cnpj` VARCHAR(18) NOT NULL,
  `inscEstadual` VARCHAR(20) NOT NULL,
  `antt` VARCHAR(10) NULL DEFAULT NULL,
  `tel` VARCHAR(18) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTransportadora`),
  FULLTEXT INDEX `idxFT` (`razaoSocial` ASC, `nomeFantasia` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`pedido_transportadora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedido_transportadora` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedido_transportadora` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idTransportadora` INT(10) UNSIGNED NOT NULL,
  `idPedido` VARCHAR(30) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `dataEmissao` DATE NOT NULL,
  `dataEntrega` DATE NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `idTransportadora`, `idPedido`, `tipo`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_PedidoTransportadora_Transportadora1_idx` (`idTransportadora` ASC),
  CONSTRAINT `fk_PedidoTransportadora_Transportadora1`
    FOREIGN KEY (`idTransportadora`)
    REFERENCES `mydb`.`transportadora` (`idTransportadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`produto_has_preco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`produto_has_preco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`produto_has_preco` (
  `idPreco` INT(11) NOT NULL AUTO_INCREMENT,
  `idProduto` INT(10) UNSIGNED NOT NULL,
  `preco` DECIMAL(15,4) NULL DEFAULT NULL,
  `validadeInicio` DATE NULL DEFAULT NULL,
  `validadeFim` DATE NULL DEFAULT NULL,
  `expirado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idPreco`),
  INDEX `fk_Produto_has_Preco_Produto1_idx` (`idProduto` ASC),
  INDEX `validadeFim` (`validadeFim` ASC, `expirado` ASC),
  CONSTRAINT `fk_Produto_has_Preco_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `mydb`.`produto` (`idProduto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 972408
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`profissional_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`profissional_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`profissional_has_endereco` (
  `idEndereco` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idProfissional` INT(10) UNSIGNED NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `logradouro` VARCHAR(90) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(72) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `uf` VARCHAR(45) NULL DEFAULT NULL,
  `codUF` INT(11) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Profissional_has_Endereco_Profissional1_idx` (`idProfissional` ASC),
  CONSTRAINT `fk_Profissional_has_Endereco_Profissional1`
    FOREIGN KEY (`idProfissional`)
    REFERENCES `mydb`.`profissional` (`idProfissional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`transportadora_has_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transportadora_has_endereco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transportadora_has_endereco` (
  `idEndereco` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idTransportadora` INT(10) UNSIGNED NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `logradouro` VARCHAR(90) NULL DEFAULT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(72) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `uf` VARCHAR(45) NULL DEFAULT NULL,
  `codUF` INT(11) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idEndereco`),
  INDEX `fk_Transportadora_has_Endereco_Transportadora1_idx` (`idTransportadora` ASC),
  CONSTRAINT `fk_Transportadora_has_Endereco_Transportadora1`
    FOREIGN KEY (`idTransportadora`)
    REFERENCES `mydb`.`transportadora` (`idTransportadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`transportadora_has_veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`transportadora_has_veiculo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`transportadora_has_veiculo` (
  `idVeiculo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idTransportadora` INT(10) UNSIGNED NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `carga` INT(11) NOT NULL,
  `placa` VARCHAR(45) NULL DEFAULT NULL,
  `desativado` TINYINT(1) NOT NULL DEFAULT '0',
  `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `lastUpdated` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idVeiculo`),
  INDEX `fk_Transportadora_has_Veiculo_Transportadora1_idx` (`idTransportadora` ASC),
  CONSTRAINT `fk_Transportadora_has_Veiculo_Transportadora1`
    FOREIGN KEY (`idTransportadora`)
    REFERENCES `mydb`.`transportadora` (`idTransportadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo_has_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`veiculo_has_produto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`veiculo_has_produto` (
  `idVeiculo` INT(11) NOT NULL,
  `idProduto` INT(11) NOT NULL,
  `idEvento` INT(11) NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `data` DATETIME NOT NULL,
  PRIMARY KEY (`idVeiculo`, `idProduto`, `idEvento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
ROW_FORMAT = COMPRESSED;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_coleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_coleta` (`fornecedor` INT, `numeroNFe` INT, `produto` INT, `quant` INT, `un` INT, `caixas` INT, `kgcx` INT, `idVenda` INT, `ordemCompra` INT, `local` INT, `dataRealCompra` INT, `dataRealConf` INT, `dataRealFat` INT, `dataPrevColeta` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_compras` (`OC` INT, `Compra` INT, `Código` INT, `Fornecedor` INT, `Produtos` INT, `Total` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_estoque` (`Status` INT, `idEstoque` INT, `Fornecedor` INT, `Produto` INT, `Quant` INT, `un` INT, `un2` INT, `Caixas M2` INT, `Caixas PÇ` INT, `Cód Com` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_faturamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_faturamento` (`OC` INT, `Compra` INT, `Código` INT, `Fornecedor` INT, `Produtos` INT, `Total` INT, `representacao` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_fornecedor_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_fornecedor_compra` (`fornecedor` INT, `PEND` INT, `CONF` INT, `FAT` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_fornecedor_logistica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_fornecedor_logistica` (`Fornecedor` INT, `COLET` INT, `RECEB` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_fornecedor_logistica_coleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_fornecedor_logistica_coleta` (`Fornecedor` INT, `COLET` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_fornecedor_logistica_recebimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_fornecedor_logistica_recebimento` (`Fornecedor` INT, `RECEB` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_fornecedor_logistica_representacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_fornecedor_logistica_representacao` (`Fornecedor` INT, `Produtos` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_logistica_representacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_logistica_representacao` (`fornecedor` INT, `Código` INT, `Cliente` INT, `Produtos` INT, `Peso Kg` INT, `status` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_nfe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_nfe` (`tipo` INT, `NFe` INT, `OC` INT, `Venda` INT, `CPF` INT, `CNPJ` INT, `Cliente` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_orcamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_orcamento` (`idLoja` INT, `idUsuario` INT, `Código` INT, `Vendedor` INT, `Indicou` INT, `Cliente` INT, `Tel` INT, `Cel` INT, `Tel Com` INT, `Data` INT, `Total` INT, `Status` INT, `Dias restantes` INT, `Data Próx Followup` INT, `Observação` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_produto_estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_produto_estoque` (`selecionado` INT, `status` INT, `idVendaProduto` INT, `idNfeSaida` INT, `fornecedor` INT, `idVenda` INT, `idLoja` INT, `idProduto` INT, `produto` INT, `obs` INT, `prcUnitario` INT, `caixas` INT, `quant` INT, `un` INT, `unCaixa` INT, `codComercial` INT, `formComercial` INT, `parcial` INT, `desconto` INT, `parcialDesc` INT, `descGlobal` INT, `total` INT, `idCompra` INT, `dataPrevCompra` INT, `dataRealCompra` INT, `dataPrevConf` INT, `dataRealConf` INT, `dataPrevFat` INT, `dataRealFat` INT, `dataPrevColeta` INT, `dataRealColeta` INT, `dataPrevReceb` INT, `dataRealReceb` INT, `dataPrevEnt` INT, `dataRealEnt` INT, `created` INT, `lastUpdated` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_produto_pendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_produto_pendente` (`status` INT, `idVendaProduto` INT, `fornecedor` INT, `idVenda` INT, `idProduto` INT, `produto` INT, `colecao` INT, `formComercial` INT, `quant` INT, `un` INT, `Un2` INT, `Caixas` INT, `kgcx` INT, `codComercial` INT, `codBarras` INT, `custo` INT, `idCompra` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_produtos_pendentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_produtos_pendentes` (`Fornecedor` INT, `Descrição` INT, `Form` INT, `Quant` INT, `Un` INT, `Un2` INT, `Caixas` INT, `Cód Com` INT, `idCompra` INT, `Status` INT, `Mês` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_recebimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_recebimento` (`fornecedor` INT, `numeroNFe` INT, `produto` INT, `quant` INT, `un` INT, `caixas` INT, `idVenda` INT, `ordemCompra` INT, `local` INT, `Dias restantes` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_relatorio` (`Loja` INT, `Vendedor` INT, `idUsuario` INT, `idVenda` INT, `Mês` INT, `Faturamento` INT, `Valor Comissão` INT, `% Comissão` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_relatorio_loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_relatorio_loja` (`Loja` INT, `Faturamento` INT, `Valor Comissão` INT, `% Comissão` INT, `Mês` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_relatorio_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_relatorio_vendedor` (`Loja` INT, `Vendedor` INT, `idUsuario` INT, `Faturamento` INT, `Valor Comissão` INT, `% Comissão` INT, `Mês` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_resumo_relatorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_resumo_relatorio` (`Loja` INT, `Vendedor` INT, `Validos Anteriores` INT, `Gerados Mes` INT, `Revalidados Mes` INT, `Fechados Mes` INT, `Perdidos Mes` INT, `Validos Mes` INT, `% Fechados / Gerados` INT, `% Fechados / Carteira` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_validacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_validacao` (`idVenda` INT, `soma` INT, `total` INT, `Pag.` INT, `Dif` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_venda` (`idLoja` INT, `idUsuario` INT, `Código` INT, `Vendedor` INT, `Indicou` INT, `Cliente` INT, `Data` INT, `Total R$` INT, `Status` INT, `statusEntrega` INT, `Dias restantes` INT);

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view_venda_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view_venda_produto` (`data` INT, `fornecedor` INT, `idVenda` INT, `produto` INT, `caixas` INT, `quant` INT, `un` INT, `codComercial` INT, `formComercial` INT, `status` INT);

-- -----------------------------------------------------
-- function digits
-- -----------------------------------------------------

USE `mydb`;
DROP function IF EXISTS `mydb`.`digits`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`%` FUNCTION `digits`( str CHAR(32) ) RETURNS char(32) CHARSET utf8
BEGIN
  DECLARE i, len SMALLINT DEFAULT 1;
  DECLARE ret CHAR(32) DEFAULT '';
  DECLARE c CHAR(1);

  IF str IS NULL
  THEN 
    RETURN "";
  END IF;

  SET len = CHAR_LENGTH( str );
  REPEAT
    BEGIN
      SET c = MID( str, i, 1 );
      IF c BETWEEN '0' AND '9' THEN 
        SET ret=CONCAT(ret,c);
      END IF;
      SET i = i + 1;
    END;
  UNTIL i > len END REPEAT;
  RETURN ret;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure invalidate_expired
-- -----------------------------------------------------

USE `mydb`;
DROP procedure IF EXISTS `mydb`.`invalidate_expired`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `invalidate_expired`()
BEGIN 

UPDATE produto_has_preco 
SET 
    expirado = TRUE
WHERE
    validadeFim < CURDATE();
    
    -- se nao tiver preço valido marca produto como descontinuado                
UPDATE produto 
SET 
    descontinuado = TRUE
WHERE
    descontinuado = FALSE
        AND idProduto NOT IN (SELECT 
            idProduto
        FROM
            produto_has_preco
        WHERE
            expirado = FALSE);

-- copia o preço valido para produto
UPDATE produto AS p,
    produto_has_preco AS prc 
SET 
    p.precovenda = prc.preco,
    p.validade = prc.validadeFim
WHERE
    p.idProduto = prc.idProduto
        AND prc.expirado = FALSE
        AND p.descontinuado = FALSE
        AND p.validade != prc.validadeFim;
        
END$$

DELIMITER ;

-- -----------------------------------------------------
-- function mydate
-- -----------------------------------------------------

USE `mydb`;
DROP function IF EXISTS `mydb`.`mydate`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`%` FUNCTION `mydate`() RETURNS varchar(10) CHARSET utf8
    NO SQL
    DETERMINISTIC
return @mydate$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure relatorio
-- -----------------------------------------------------

USE `mydb`;
DROP procedure IF EXISTS `mydb`.`relatorio`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `relatorio`(mes varchar(20))
BEGIN
select * from view_relatorio where Mês = mes;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure update_orcamento_status
-- -----------------------------------------------------

USE `mydb`;
DROP procedure IF EXISTS `mydb`.`update_orcamento_status`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `update_orcamento_status`()
BEGIN
UPDATE orcamento 
SET 
    status = 'EXPIRADO'
WHERE
    NOW() > DATE_ADD(data, INTERVAL validade DAY)
        AND status = 'ATIVO';
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure update_venda_status
-- -----------------------------------------------------

USE `mydb`;
DROP procedure IF EXISTS `mydb`.`update_venda_status`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `update_venda_status`()
BEGIN 

	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'ESTOQUE';
	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'EM RECEBIMENTO';
	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'EM COLETA';
	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'EM FATURAMENTO';
	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'EM COMPRA';
	UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'INICIADO';
    UPDATE venda AS v, venda_has_produto AS p SET v.status = p.status WHERE v.idVenda = p.idVenda AND p.status = 'PENDENTE';
    
	UPDATE venda AS v, venda_has_produto AS p SET v.statusEntrega = p.status WHERE v.idVenda = p.idVenda AND p.status = 'ESTOQUE';
        
END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`view_coleta`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_coleta` ;
DROP TABLE IF EXISTS `mydb`.`view_coleta`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`%` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_coleta` AS
    SELECT 
        `f`.`razaoSocial` AS `fornecedor`,
        `e`.`numeroNFe` AS `numeroNFe`,
        `e`.`descricao` AS `produto`,
        ABS(`e`.`quant`) AS `quant`,
        `e`.`un` AS `un`,
        `e`.`caixas` AS `caixas`,
        `p`.`kgcx` AS `kgcx`,
        `vp`.`idVenda` AS `idVenda`,
        `e`.`ordemCompra` AS `ordemCompra`,
        `e`.`local` AS `local`,
        `vp`.`dataRealCompra` AS `dataRealCompra`,
        `vp`.`dataRealConf` AS `dataRealConf`,
        `vp`.`dataRealFat` AS `dataRealFat`,
        `vp`.`dataPrevColeta` AS `dataPrevColeta`
    FROM
        (((`mydb`.`estoque` `e`
        LEFT JOIN `mydb`.`venda_has_produto` `vp` ON ((`e`.`idProduto` = `vp`.`idProduto`)))
        LEFT JOIN `mydb`.`produto` `p` ON ((`e`.`idProduto` = `p`.`idProduto`)))
        LEFT JOIN `mydb`.`fornecedor` `f` ON ((`f`.`idFornecedor` = `p`.`idFornecedor`)))
    WHERE
        ((`e`.`status` = 'EM COLETA')
            AND (`f`.`coleta` = 1))
    GROUP BY `e`.`idEstoque` DESC;

-- -----------------------------------------------------
-- View `mydb`.`view_compras`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_compras` ;
DROP TABLE IF EXISTS `mydb`.`view_compras`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_compras` AS
    SELECT 
        `p`.`ordemCompra` AS `OC`,
        `p`.`idCompra` AS `Compra`,
        GROUP_CONCAT(DISTINCT `p`.`idVenda`
            SEPARATOR ',') AS `Código`,
        `p`.`fornecedor` AS `Fornecedor`,
        COUNT(`p`.`idProduto`) AS `Produtos`,
        SUM(`p`.`preco`) AS `Total`
    FROM
        `mydb`.`pedido_fornecedor_has_produto` `p`
    WHERE
        (`p`.`status` = 'EM COMPRA')
    GROUP BY `p`.`idCompra`;

-- -----------------------------------------------------
-- View `mydb`.`view_estoque`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_estoque` ;
DROP TABLE IF EXISTS `mydb`.`view_estoque`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_estoque` AS
    SELECT 
        `e`.`status` AS `Status`,
        `e`.`idEstoque` AS `idEstoque`,
        `p`.`fornecedor` AS `Fornecedor`,
        `e`.`descricao` AS `Produto`,
        SUM(`e`.`quant`) AS `Quant`,
        `p`.`un` AS `un`,
        `p`.`un2` AS `un2`,
        (`e`.`quant` / `p`.`m2cx`) AS `Caixas M2`,
        (`e`.`quant` / `p`.`pccx`) AS `Caixas PÇ`,
        `e`.`codComercial` AS `Cód Com`
    FROM
        (`mydb`.`estoque` `e`
        LEFT JOIN `mydb`.`produto` `p` ON ((`e`.`idProduto` = `p`.`idProduto`)))
    GROUP BY `e`.`idEstoque`;

-- -----------------------------------------------------
-- View `mydb`.`view_faturamento`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_faturamento` ;
DROP TABLE IF EXISTS `mydb`.`view_faturamento`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_faturamento` AS
    SELECT 
        `p`.`ordemCompra` AS `OC`,
        `p`.`idCompra` AS `Compra`,
        `p`.`idVenda` AS `Código`,
        `p`.`fornecedor` AS `Fornecedor`,
        COUNT(`p`.`idProduto`) AS `Produtos`,
        SUM(`p`.`preco`) AS `Total`,
        `f`.`representacao` AS `representacao`
    FROM
        (`mydb`.`pedido_fornecedor_has_produto` `p`
        LEFT JOIN `mydb`.`fornecedor` `f` ON ((`p`.`fornecedor` = `f`.`razaoSocial`)))
    WHERE
        (`p`.`status` = 'EM FATURAMENTO')
    GROUP BY `p`.`idCompra`;

-- -----------------------------------------------------
-- View `mydb`.`view_fornecedor_compra`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_fornecedor_compra` ;
DROP TABLE IF EXISTS `mydb`.`view_fornecedor_compra`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_fornecedor_compra` AS
    SELECT 
        `mydb`.`pedido_fornecedor_has_produto`.`fornecedor` AS `fornecedor`,
        SUM((CASE
            WHEN (`mydb`.`pedido_fornecedor_has_produto`.`status` = 'PENDENTE') THEN 1
            ELSE 0
        END)) AS `PEND`,
        SUM((CASE
            WHEN (`mydb`.`pedido_fornecedor_has_produto`.`status` = 'EM COMPRA') THEN 1
            ELSE 0
        END)) AS `CONF`,
        SUM((CASE
            WHEN (`mydb`.`pedido_fornecedor_has_produto`.`status` = 'EM FATURAMENTO') THEN 1
            ELSE 0
        END)) AS `FAT`
    FROM
        `mydb`.`pedido_fornecedor_has_produto`
    WHERE
        ((`mydb`.`pedido_fornecedor_has_produto`.`status` = 'PENDENTE')
            OR (`mydb`.`pedido_fornecedor_has_produto`.`status` = 'INICIADO')
            OR (`mydb`.`pedido_fornecedor_has_produto`.`status` = 'EM COMPRA')
            OR (`mydb`.`pedido_fornecedor_has_produto`.`status` = 'EM FATURAMENTO'))
    GROUP BY `mydb`.`pedido_fornecedor_has_produto`.`fornecedor`;

-- -----------------------------------------------------
-- View `mydb`.`view_fornecedor_logistica`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_fornecedor_logistica` ;
DROP TABLE IF EXISTS `mydb`.`view_fornecedor_logistica`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_fornecedor_logistica` AS
    SELECT 
        `f`.`razaoSocial` AS `Fornecedor`,
        SUM((CASE
            WHEN (`e`.`status` = 'EM COLETA') THEN 1
            ELSE 0
        END)) AS `COLET`,
        SUM((CASE
            WHEN (`e`.`status` = 'EM RECEBIMENTO') THEN 1
            ELSE 0
        END)) AS `RECEB`
    FROM
        ((`mydb`.`estoque` `e`
        LEFT JOIN `mydb`.`produto` `p` ON ((`e`.`idProduto` = `p`.`idProduto`)))
        LEFT JOIN `mydb`.`fornecedor` `f` ON ((`p`.`idFornecedor` = `f`.`idFornecedor`)))
    WHERE
        (((`e`.`status` = 'EM COLETA')
            AND (`f`.`coleta` = 1))
            OR (`e`.`status` = 'EM RECEBIMENTO'))
    GROUP BY `f`.`razaoSocial`;

-- -----------------------------------------------------
-- View `mydb`.`view_fornecedor_logistica_coleta`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_fornecedor_logistica_coleta` ;
DROP TABLE IF EXISTS `mydb`.`view_fornecedor_logistica_coleta`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_fornecedor_logistica_coleta` AS
    SELECT 
        `f`.`razaoSocial` AS `Fornecedor`,
        SUM((CASE
            WHEN (`e`.`status` = 'EM COLETA') THEN 1
            ELSE 0
        END)) AS `COLET`
    FROM
        ((`mydb`.`estoque` `e`
        LEFT JOIN `mydb`.`produto` `p` ON ((`e`.`idProduto` = `p`.`idProduto`)))
        LEFT JOIN `mydb`.`fornecedor` `f` ON ((`p`.`idFornecedor` = `f`.`idFornecedor`)))
    WHERE
        ((`e`.`status` = 'EM COLETA')
            AND (`f`.`coleta` = 1))
    GROUP BY `f`.`razaoSocial`;

-- -----------------------------------------------------
-- View `mydb`.`view_fornecedor_logistica_recebimento`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_fornecedor_logistica_recebimento` ;
DROP TABLE IF EXISTS `mydb`.`view_fornecedor_logistica_recebimento`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_fornecedor_logistica_recebimento` AS
    SELECT 
        `f`.`razaoSocial` AS `Fornecedor`,
        SUM((CASE
            WHEN (`e`.`status` = 'EM RECEBIMENTO') THEN 1
            ELSE 0
        END)) AS `RECEB`
    FROM
        ((`mydb`.`estoque` `e`
        LEFT JOIN `mydb`.`produto` `p` ON ((`e`.`idProduto` = `p`.`idProduto`)))
        LEFT JOIN `mydb`.`fornecedor` `f` ON ((`p`.`idFornecedor` = `f`.`idFornecedor`)))
    WHERE
        (`e`.`status` = 'EM RECEBIMENTO')
    GROUP BY `f`.`razaoSocial`;

-- -----------------------------------------------------
-- View `mydb`.`view_fornecedor_logistica_representacao`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_fornecedor_logistica_representacao` ;
DROP TABLE IF EXISTS `mydb`.`view_fornecedor_logistica_representacao`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_fornecedor_logistica_representacao` AS
    SELECT 
        `f`.`razaoSocial` AS `Fornecedor`,
        COUNT(`pf`.`idProduto`) AS `Produtos`
    FROM
        (`mydb`.`pedido_fornecedor_has_produto` `pf`
        LEFT JOIN `mydb`.`fornecedor` `f` ON ((`pf`.`fornecedor` = `f`.`razaoSocial`)))
    WHERE
        ((`pf`.`status` = 'EM COLETA')
            AND (`f`.`representacao` = 1))
    GROUP BY `f`.`razaoSocial`;

-- -----------------------------------------------------
-- View `mydb`.`view_logistica_representacao`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_logistica_representacao` ;
DROP TABLE IF EXISTS `mydb`.`view_logistica_representacao`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_logistica_representacao` AS
    SELECT 
        `pf`.`fornecedor` AS `fornecedor`,
        `pf`.`idVenda` AS `Código`,
        `c`.`nome_razao` AS `Cliente`,
        COUNT(`p`.`descricao`) AS `Produtos`,
        `p`.`kgcx` AS `Peso Kg`,
        `pf`.`status` AS `status`
    FROM
        (((((`mydb`.`pedido_fornecedor_has_produto` `pf`
        LEFT JOIN `mydb`.`fornecedor` `f` ON ((`pf`.`fornecedor` = `f`.`razaoSocial`)))
        LEFT JOIN `mydb`.`nfe` `n` ON ((`pf`.`idNFe` = `n`.`idNFe`)))
        LEFT JOIN `mydb`.`produto` `p` ON ((`pf`.`idProduto` = `p`.`idProduto`)))
        LEFT JOIN `mydb`.`venda` `v` ON ((`pf`.`idVenda` = `v`.`idVenda`)))
        LEFT JOIN `mydb`.`cliente` `c` ON ((`v`.`idCliente` = `c`.`idCliente`)))
    GROUP BY `pf`.`idVenda`;

-- -----------------------------------------------------
-- View `mydb`.`view_nfe`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_nfe` ;
DROP TABLE IF EXISTS `mydb`.`view_nfe`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_nfe` AS
    SELECT 
        `n`.`tipo` AS `tipo`,
        `n`.`numeroNFe` AS `NFe`,
        `pf`.`ordemCompra` AS `OC`,
        `v`.`idVenda` AS `Venda`,
        `c`.`cpf` AS `CPF`,
        `c`.`cnpj` AS `CNPJ`,
        `c`.`nome_razao` AS `Cliente`
    FROM
        (((((`mydb`.`nfe` `n`
        LEFT JOIN `mydb`.`estoque_has_nfe` `ehn` ON ((`n`.`idNFe` = `ehn`.`idNFe`)))
        LEFT JOIN `mydb`.`estoque` `e` ON ((`ehn`.`idEstoque` = `e`.`idEstoque`)))
        LEFT JOIN `mydb`.`pedido_fornecedor_has_produto` `pf` ON ((`e`.`ordemCompra` = `pf`.`ordemCompra`)))
        LEFT JOIN `mydb`.`venda` `v` ON ((`pf`.`idVenda` = `v`.`idVenda`)))
        LEFT JOIN `mydb`.`cliente` `c` ON ((`v`.`idCliente` = `c`.`idCliente`)))
    GROUP BY `n`.`tipo` , `n`.`numeroNFe`;

-- -----------------------------------------------------
-- View `mydb`.`view_orcamento`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_orcamento` ;
DROP TABLE IF EXISTS `mydb`.`view_orcamento`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_orcamento` AS
    SELECT 
        `u`.`idLoja` AS `idLoja`,
        `u`.`idUsuario` AS `idUsuario`,
        `o`.`idOrcamento` AS `Código`,
        `u`.`nome` AS `Vendedor`,
        `u2`.`nome` AS `Indicou`,
        `c`.`nome_razao` AS `Cliente`,
        `c`.`tel` AS `Tel`,
        `c`.`telCel` AS `Cel`,
        `c`.`telCom` AS `Tel Com`,
        `o`.`data` AS `Data`,
        `o`.`total` AS `Total`,
        `o`.`status` AS `Status`,
        (`o`.`validade` - (TO_DAYS(NOW()) - TO_DAYS(`o`.`data`))) AS `Dias restantes`,
        `fl1`.`dataProxFollowup` AS `Data Próx Followup`,
        `fl1`.`observacao` AS `Observação`
    FROM
        (((((`mydb`.`orcamento` `o`
        LEFT JOIN `mydb`.`cliente` `c` ON ((`o`.`idCliente` = `c`.`idCliente`)))
        LEFT JOIN `mydb`.`usuario` `u` ON ((`o`.`idUsuario` = `u`.`idUsuario`)))
        LEFT JOIN `mydb`.`orcamento_has_followup` `fl1` ON ((`fl1`.`idOrcamento` LIKE CONCAT(LEFT(`o`.`idOrcamento`, 11), '%'))))
        LEFT JOIN `mydb`.`orcamento_has_followup` `fl2` ON (((`fl1`.`idOrcamento` LIKE CONCAT(LEFT(`fl2`.`idOrcamento`, 11), '%'))
            AND (`fl1`.`dataProxFollowup` < `fl2`.`dataProxFollowup`))))
        LEFT JOIN `mydb`.`usuario` `u2` ON ((`o`.`idUsuarioIndicou` = `u2`.`idUsuario`)))
    WHERE
        ISNULL(`fl2`.`idOrcamento`);

-- -----------------------------------------------------
-- View `mydb`.`view_produto_estoque`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_produto_estoque` ;
DROP TABLE IF EXISTS `mydb`.`view_produto_estoque`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`%` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_produto_estoque` AS
    SELECT 
        `v`.`selecionado` AS `selecionado`,
        `v`.`status` AS `status`,
        `v`.`idVendaProduto` AS `idVendaProduto`,
        `v`.`idNfeSaida` AS `idNfeSaida`,
        `v`.`fornecedor` AS `fornecedor`,
        `v`.`idVenda` AS `idVenda`,
        `v`.`idLoja` AS `idLoja`,
        `v`.`idProduto` AS `idProduto`,
        `v`.`produto` AS `produto`,
        `v`.`obs` AS `obs`,
        `v`.`prcUnitario` AS `prcUnitario`,
        `v`.`caixas` AS `caixas`,
        `v`.`quant` AS `quant`,
        `v`.`un` AS `un`,
        `v`.`unCaixa` AS `unCaixa`,
        `v`.`codComercial` AS `codComercial`,
        `v`.`formComercial` AS `formComercial`,
        `v`.`parcial` AS `parcial`,
        `v`.`desconto` AS `desconto`,
        `v`.`parcialDesc` AS `parcialDesc`,
        `v`.`descGlobal` AS `descGlobal`,
        `v`.`total` AS `total`,
        `v`.`idCompra` AS `idCompra`,
        `v`.`dataPrevCompra` AS `dataPrevCompra`,
        `v`.`dataRealCompra` AS `dataRealCompra`,
        `v`.`dataPrevConf` AS `dataPrevConf`,
        `v`.`dataRealConf` AS `dataRealConf`,
        `v`.`dataPrevFat` AS `dataPrevFat`,
        `v`.`dataRealFat` AS `dataRealFat`,
        `v`.`dataPrevColeta` AS `dataPrevColeta`,
        `v`.`dataRealColeta` AS `dataRealColeta`,
        `v`.`dataPrevReceb` AS `dataPrevReceb`,
        `v`.`dataRealReceb` AS `dataRealReceb`,
        `v`.`dataPrevEnt` AS `dataPrevEnt`,
        `v`.`dataRealEnt` AS `dataRealEnt`,
        `v`.`created` AS `created`,
        `v`.`lastUpdated` AS `lastUpdated`
    FROM
        `mydb`.`venda_has_produto` `v`;

-- -----------------------------------------------------
-- View `mydb`.`view_produto_pendente`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_produto_pendente` ;
DROP TABLE IF EXISTS `mydb`.`view_produto_pendente`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_produto_pendente` AS
    SELECT 
        `v`.`status` AS `status`,
        `v`.`idVendaProduto` AS `idVendaProduto`,
        `v`.`fornecedor` AS `fornecedor`,
        `v`.`idVenda` AS `idVenda`,
        `v`.`idProduto` AS `idProduto`,
        `v`.`produto` AS `produto`,
        `p`.`colecao` AS `colecao`,
        `v`.`formComercial` AS `formComercial`,
        `v`.`quant` AS `quant`,
        `v`.`un` AS `un`,
        `p`.`un2` AS `Un2`,
        `v`.`caixas` AS `Caixas`,
        `p`.`kgcx` AS `kgcx`,
        `v`.`codComercial` AS `codComercial`,
        `p`.`codBarras` AS `codBarras`,
        `p`.`custo` AS `custo`,
        `v`.`idCompra` AS `idCompra`
    FROM
        (`mydb`.`venda_has_produto` `v`
        LEFT JOIN `mydb`.`produto` `p` ON ((`v`.`idProduto` = `p`.`idProduto`)));

-- -----------------------------------------------------
-- View `mydb`.`view_produtos_pendentes`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_produtos_pendentes` ;
DROP TABLE IF EXISTS `mydb`.`view_produtos_pendentes`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_produtos_pendentes` AS
    SELECT 
        `vp`.`fornecedor` AS `Fornecedor`,
        `vp`.`produto` AS `Descrição`,
        `vp`.`formComercial` AS `Form`,
        SUM(`vp`.`quant`) AS `Quant`,
        `vp`.`un` AS `Un`,
        `p`.`un2` AS `Un2`,
        `vp`.`caixas` AS `Caixas`,
        `vp`.`codComercial` AS `Cód Com`,
        `vp`.`idCompra` AS `idCompra`,
        `vp`.`status` AS `Status`,
        MONTHNAME(`v`.`data`) AS `Mês`
    FROM
        ((`mydb`.`venda_has_produto` `vp`
        LEFT JOIN `mydb`.`venda` `v` ON ((`v`.`idVenda` = `vp`.`idVenda`)))
        LEFT JOIN `mydb`.`produto` `p` ON ((`p`.`idProduto` = `vp`.`idProduto`)))
    GROUP BY `vp`.`status` , `vp`.`codComercial` , `Mês`;

-- -----------------------------------------------------
-- View `mydb`.`view_recebimento`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_recebimento` ;
DROP TABLE IF EXISTS `mydb`.`view_recebimento`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`%` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_recebimento` AS
    SELECT 
        `f`.`razaoSocial` AS `fornecedor`,
        `e`.`numeroNFe` AS `numeroNFe`,
        `e`.`descricao` AS `produto`,
        ABS(`e`.`quant`) AS `quant`,
        `e`.`un` AS `un`,
        `e`.`caixas` AS `caixas`,
        `vp`.`idVenda` AS `idVenda`,
        `e`.`ordemCompra` AS `ordemCompra`,
        `e`.`local` AS `local`,
        `vp`.`dataPrevColeta` AS `Dias restantes`
    FROM
        (((`mydb`.`estoque` `e`
        LEFT JOIN `mydb`.`venda_has_produto` `vp` ON ((`e`.`idProduto` = `vp`.`idProduto`)))
        LEFT JOIN `mydb`.`produto` `p` ON ((`e`.`idProduto` = `p`.`idProduto`)))
        LEFT JOIN `mydb`.`fornecedor` `f` ON ((`p`.`idFornecedor` = `f`.`idFornecedor`)))
    WHERE
        (`e`.`status` = 'EM RECEBIMENTO')
    GROUP BY `e`.`idEstoque` DESC;

-- -----------------------------------------------------
-- View `mydb`.`view_relatorio`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_relatorio` ;
DROP TABLE IF EXISTS `mydb`.`view_relatorio`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_relatorio` AS
    SELECT 
        `l`.`descricao` AS `Loja`,
        `u`.`nome` AS `Vendedor`,
        `u`.`idUsuario` AS `idUsuario`,
        `v`.`idVenda` AS `idVenda`,
        DATE_FORMAT(`v`.`data`, '%Y-%m') AS `Mês`,
        SUM(`vp`.`total`) AS `Faturamento`,
        IF((RIGHT(`p`.`ui`, 1) = 'L'),
            (SUM(`vp`.`total`) * `f`.`comissao2`),
            (SUM(`vp`.`total`) * `f`.`comissao1`)) AS `Valor Comissão`,
        IF((RIGHT(`p`.`ui`, 1) = 'L'),
            `f`.`comissao2`,
            `f`.`comissao1`) AS `% Comissão`
    FROM
        (((((`mydb`.`venda` `v`
        LEFT JOIN `mydb`.`venda_has_produto` `vp` ON ((`v`.`idVenda` = `vp`.`idVenda`)))
        LEFT JOIN `mydb`.`loja` `l` ON ((`l`.`idLoja` = `v`.`idLoja`)))
        LEFT JOIN `mydb`.`usuario` `u` ON ((`u`.`idUsuario` = `v`.`idUsuario`)))
        LEFT JOIN `mydb`.`produto` `p` ON ((`p`.`idProduto` = `vp`.`idProduto`)))
        LEFT JOIN `mydb`.`fornecedor` `f` ON ((`f`.`idFornecedor` = `p`.`idFornecedor`)))
    WHERE
        (`v`.`status` <> 'CANCELADO')
    GROUP BY `vp`.`idVenda` , IF((RIGHT(`p`.`ui`, 1) = 'L'),
        `f`.`comissao2`,
        `f`.`comissao1`)
    ORDER BY `l`.`descricao` , `u`.`nome` , `v`.`idVenda`;

-- -----------------------------------------------------
-- View `mydb`.`view_relatorio_loja`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_relatorio_loja` ;
DROP TABLE IF EXISTS `mydb`.`view_relatorio_loja`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_relatorio_loja` AS
    SELECT 
        `v`.`Loja` AS `Loja`,
        SUM(`v`.`Faturamento`) AS `Faturamento`,
        SUM(`v`.`Valor Comissão`) AS `Valor Comissão`,
        (SUM(`v`.`Valor Comissão`) / SUM(`v`.`Faturamento`)) AS `% Comissão`,
        `v`.`Mês` AS `Mês`
    FROM
        (`mydb`.`view_relatorio` `v`
        LEFT JOIN `mydb`.`usuario` `u` ON ((`v`.`Vendedor` = `u`.`nome`)))
    GROUP BY `v`.`Loja` , `v`.`Mês`;

-- -----------------------------------------------------
-- View `mydb`.`view_relatorio_vendedor`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_relatorio_vendedor` ;
DROP TABLE IF EXISTS `mydb`.`view_relatorio_vendedor`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_relatorio_vendedor` AS
    SELECT 
        `v`.`Loja` AS `Loja`,
        `v`.`Vendedor` AS `Vendedor`,
        `v`.`idUsuario` AS `idUsuario`,
        SUM(`v`.`Faturamento`) AS `Faturamento`,
        SUM(`v`.`Valor Comissão`) AS `Valor Comissão`,
        (SUM(`v`.`Valor Comissão`) / SUM(`v`.`Faturamento`)) AS `% Comissão`,
        `v`.`Mês` AS `Mês`
    FROM
        (`mydb`.`view_relatorio` `v`
        LEFT JOIN `mydb`.`usuario` `u` ON ((`v`.`Vendedor` = `u`.`nome`)))
    GROUP BY `u`.`nome` , `v`.`Loja` , `v`.`Mês`
    ORDER BY `v`.`Loja`;

-- -----------------------------------------------------
-- View `mydb`.`view_resumo_relatorio`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_resumo_relatorio` ;
DROP TABLE IF EXISTS `mydb`.`view_resumo_relatorio`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`%` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_resumo_relatorio` AS
    SELECT 
        `l`.`descricao` AS `Loja`,
        `u`.`user` AS `Vendedor`,
        SUM(IF(((DATE_FORMAT(`o`.`data`, '%Y-%m') < MYDATE())
                AND ((`o`.`status` = 'ATIVO')
                OR (`o`.`status` = 'EXPIRADO')
                OR ((`o`.`status` = 'FECHADO')
                AND (DATE_FORMAT(`v`.`data`, '%Y-%m') >= MYDATE()))
                OR ((`o`.`status` = 'PERDIDO')
                AND (DATE_FORMAT(`o`.`lastUpdated`, '%Y-%m') >= MYDATE())))),
            `o`.`total`,
            0)) AS `Validos Anteriores`,
        SUM(IF(((DATE_FORMAT(`o`.`data`, '%Y-%m') = MYDATE())
                AND ISNULL(`o_1`.`data`)),
            `o`.`total`,
            0)) AS `Gerados Mes`,
        SUM(IF(((DATE_FORMAT(`o`.`data`, '%Y-%m') = MYDATE())
                AND (`o_1`.`data` IS NOT NULL)),
            `o`.`total`,
            0)) AS `Revalidados Mes`,
        SUM(IF(((DATE_FORMAT(`v`.`data`, '%Y-%m') = MYDATE())
                AND (`o`.`status` = 'FECHADO')),
            `o`.`total`,
            0)) AS `Fechados Mes`,
        SUM(IF(((DATE_FORMAT(`o`.`lastUpdated`, '%Y-%m') = MYDATE())
                AND (`o`.`status` = 'PERDIDO')),
            `o`.`total`,
            0)) AS `Perdidos Mes`,
        SUM(IF(((DATE_FORMAT(`o`.`data`, '%Y-%m') <= MYDATE())
                AND ((`o`.`status` = 'ATIVO')
                OR (`o`.`status` = 'EXPIRADO')
                OR ((`o`.`status` = 'FECHADO')
                AND (DATE_FORMAT(`v`.`data`, '%Y-%m') > MYDATE()))
                OR ((`o`.`status` = 'PERDIDO')
                AND (DATE_FORMAT(`o`.`lastUpdated`, '%Y-%m') > MYDATE())))),
            `o`.`total`,
            0)) AS `Validos Mes`,
        (SUM(IF(((DATE_FORMAT(`v`.`data`, '%Y-%m') = MYDATE())
                AND (`o`.`status` = 'FECHADO')),
            `o`.`total`,
            0)) / (SUM(IF(((DATE_FORMAT(`o`.`data`, '%Y-%m') = MYDATE())
                AND ISNULL(`o_1`.`data`)),
            `o`.`total`,
            0)) + SUM(IF(((DATE_FORMAT(`o`.`data`, '%Y-%m') = MYDATE())
                AND (`o_1`.`data` IS NOT NULL)),
            `o`.`total`,
            0)))) AS `% Fechados / Gerados`,
        (SUM(IF(((DATE_FORMAT(`v`.`data`, '%Y-%m') = MYDATE())
                AND (`o`.`status` = 'FECHADO')),
            `o`.`total`,
            0)) / ((SUM(IF(((DATE_FORMAT(`o`.`data`, '%Y-%m') < MYDATE())
                AND ((`o`.`status` = 'ATIVO')
                OR (`o`.`status` = 'EXPIRADO')
                OR ((`o`.`status` = 'FECHADO')
                AND (DATE_FORMAT(`v`.`data`, '%Y-%m') >= MYDATE()))
                OR ((`o`.`status` = 'PERDIDO')
                AND (DATE_FORMAT(`o`.`lastUpdated`, '%Y-%m') >= MYDATE())))),
            `o`.`total`,
            0)) + SUM(IF(((DATE_FORMAT(`o`.`data`, '%Y-%m') = MYDATE())
                AND ISNULL(`o_1`.`data`)),
            `o`.`total`,
            0))) + SUM(IF(((DATE_FORMAT(`o`.`data`, '%Y-%m') = MYDATE())
                AND (`o_1`.`data` IS NOT NULL)),
            `o`.`total`,
            0)))) AS `% Fechados / Carteira`
    FROM
        (((((((`mydb`.`orcamento` `o`
        LEFT JOIN `mydb`.`loja` `l` ON ((`o`.`idLoja` = `l`.`idLoja`)))
        LEFT JOIN `mydb`.`usuario` `u` ON ((`o`.`idUsuario` = `u`.`idUsuario`)))
        LEFT JOIN `mydb`.`cliente` `c` ON ((`o`.`idCliente` = `c`.`idCliente`)))
        LEFT JOIN `mydb`.`profissional` `p` ON ((`o`.`idProfissional` = `p`.`idProfissional`)))
        LEFT JOIN `mydb`.`orcamento` `o_1` ON ((`o`.`replicadoDe` = `o_1`.`idOrcamento`)))
        LEFT JOIN `mydb`.`orcamento_has_followup` `ohf` ON ((`o`.`idOrcamento` = `ohf`.`idOrcamento`)))
        LEFT JOIN `mydb`.`venda` `v` ON ((`o`.`idOrcamento` = `v`.`idOrcamento`)))
    WHERE
        ((`o`.`status` <> 'REPLICADO')
            AND (`o`.`status` <> 'CANCELADO'))
    GROUP BY `l`.`descricao` , `u`.`user`
    ORDER BY `l`.`descricao` , `u`.`user`;

-- -----------------------------------------------------
-- View `mydb`.`view_validacao`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_validacao` ;
DROP TABLE IF EXISTS `mydb`.`view_validacao`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_validacao` AS
    SELECT 
        `v`.`idVenda` AS `idVenda`,
        ((`v`.`subTotalLiq` + `v`.`frete`) - `v`.`descontoReais`) AS `soma`,
        `v`.`total` AS `total`,
        SUM(`c`.`valor`) AS `Pag.`,
        (SUM(`c`.`valor`) - `v`.`total`) AS `Dif`
    FROM
        (`mydb`.`venda` `v`
        LEFT JOIN `mydb`.`conta_a_receber_has_pagamento` `c` ON ((`v`.`idVenda` = `c`.`idVenda`)))
    WHERE
        ((`c`.`tipo` <> 'Crédito')
            AND (NOT ((`v`.`idVenda` LIKE '%D'))))
    GROUP BY `c`.`idVenda`;

-- -----------------------------------------------------
-- View `mydb`.`view_venda`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_venda` ;
DROP TABLE IF EXISTS `mydb`.`view_venda`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_venda` AS
    SELECT 
        `u`.`idLoja` AS `idLoja`,
        `u`.`idUsuario` AS `idUsuario`,
        `v`.`idVenda` AS `Código`,
        `u`.`nome` AS `Vendedor`,
        `u2`.`nome` AS `Indicou`,
        `c`.`nome_razao` AS `Cliente`,
        `v`.`data` AS `Data`,
        `v`.`total` AS `Total R$`,
        `v`.`status` AS `Status`,
        `v`.`statusEntrega` AS `statusEntrega`,
        ((TO_DAYS(`v`.`data`) + `v`.`prazoEntrega`) - TO_DAYS(NOW())) AS `Dias restantes`
    FROM
        (((((`mydb`.`venda` `v`
        LEFT JOIN `mydb`.`usuario` `u` ON ((`v`.`idUsuario` = `u`.`idUsuario`)))
        LEFT JOIN `mydb`.`cliente_has_endereco` `e` ON ((`v`.`idEnderecoEntrega` = `e`.`idEndereco`)))
        LEFT JOIN `mydb`.`profissional` `p` ON ((`v`.`idProfissional` = `p`.`idProfissional`)))
        LEFT JOIN `mydb`.`cliente` `c` ON ((`v`.`idCliente` = `c`.`idCliente`)))
        LEFT JOIN `mydb`.`usuario` `u2` ON ((`v`.`idUsuarioIndicou` = `u2`.`idUsuario`)));

-- -----------------------------------------------------
-- View `mydb`.`view_venda_produto`
-- -----------------------------------------------------
DROP VIEW IF EXISTS `mydb`.`view_venda_produto` ;
DROP TABLE IF EXISTS `mydb`.`view_venda_produto`;
USE `mydb`;
CREATE 
     OR REPLACE ALGORITHM = UNDEFINED 
    DEFINER = `root`@`localhost` 
    SQL SECURITY DEFINER
VIEW `mydb`.`view_venda_produto` AS
    SELECT 
        `v`.`data` AS `data`,
        `vp`.`fornecedor` AS `fornecedor`,
        `vp`.`idVenda` AS `idVenda`,
        `vp`.`produto` AS `produto`,
        `vp`.`caixas` AS `caixas`,
        `vp`.`quant` AS `quant`,
        `vp`.`un` AS `un`,
        `vp`.`codComercial` AS `codComercial`,
        `vp`.`formComercial` AS `formComercial`,
        `vp`.`status` AS `status`
    FROM
        (`mydb`.`venda` `v`
        LEFT JOIN `mydb`.`venda_has_produto` `vp` ON ((`v`.`idVenda` = `vp`.`idVenda`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
